// dashboard/src/components/CellTooltip.svelte
<script lang="ts">
  interface CellData {
    date: string;
    status: string;
    uploadedAt: string | null;
    sizeMb: number | null;
  }

  interface CellTooltipProps {
    cellData: CellData;
    position: { x: number; y: number };
  }

  const STATUS_MAP: Record<string, { text: string; className: string }> = {
    collected: { text: '\u2705 Collected & Uploaded', className: 'text-success' },
    missing: { text: '\u274C Missing', className: 'text-error' },
    partial: { text: '\u26A0\uFE0F Partial', className: 'text-warning' },
    outside: { text: 'Outside active range', className: '' },
  };

  const DEFAULT_STATUS = { text: '', className: '' };

  let { cellData, position }: CellTooltipProps = $props();

  let tooltipEl: HTMLDivElement;
  let style = $state<{ top: number; left: number; opacity: number }>({ top: -9999, left: -9999, opacity: 0 });

  const mapped = $derived(STATUS_MAP[cellData.status] ?? { ...DEFAULT_STATUS, text: cellData.status });
  const statusText = $derived(mapped.text);
  const statusClass = $derived(mapped.className);

  $effect(() => {
    // Track dependencies
    position;
    cellData;

    if (!tooltipEl || !position) return;

    const rect = tooltipEl.getBoundingClientRect();
    const padding = 12; // distance from cursor

    let left = position.x + padding;
    let top = position.y + padding;

    // Check right edge
    if (left + rect.width > window.innerWidth - padding) {
      left = position.x - rect.width - padding;
    }

    // Check bottom edge
    if (top + rect.height > window.innerHeight - padding) {
      top = position.y - rect.height - padding;
    }

    style = {
      left: Math.max(padding, left),
      top: Math.max(padding, top),
      opacity: 1,
    };
  });
</script>

{#if cellData && position}
  <div
    bind:this={tooltipEl}
    role="tooltip"
    class="bg-neutral text-neutral-content p-4 rounded-lg shadow-xl text-sm z-50 pointer-events-none fixed space-y-1"
    style="top: {style.top}px; left: {style.left}px; opacity: {style.opacity};"
  >
    <div class="font-bold border-b border-neutral-content/20 pb-1 mb-2">
      {cellData.date}
    </div>
    <div class={statusClass || undefined}>
      {statusText}
    </div>

    {#if cellData.uploadedAt}
      <div class="text-xs opacity-70 mt-2">
        <span>Uploaded:</span>{' '}
        <span>{new Date(cellData.uploadedAt).toLocaleString()}</span>
      </div>
    {/if}
    {#if cellData.sizeMb}
      <div class="text-xs opacity-70">
        <span>Size:</span>{' '}
        <span>{cellData.sizeMb.toFixed(2)} MB</span>
      </div>
    {/if}
  </div>
{/if}

// dashboard/src/components/CellTooltip.jsx
import { useEffect, useRef, useState } from 'preact/compat';
import { createPortal } from 'preact/compat';
import clsx from 'clsx';

export function CellTooltip({ cellData, position }) {
  const tooltipRef = useRef(null);
  const [style, setStyle] = useState({ top: -9999, left: -9999, opacity: 0 });

  useEffect(() => {
    if (!tooltipRef.current || !position) return;

    const rect = tooltipRef.current.getBoundingClientRect();
    const padding = 12; // distance from cursor

    let left = position.x + padding;
    let top = position.y + padding;

    // Check right edge
    if (left + rect.width > window.innerWidth - padding) {
      left = position.x - rect.width - padding;
    }

    // Check bottom edge
    if (top + rect.height > window.innerHeight - padding) {
      top = position.y - rect.height - padding;
    }

    setStyle({
      left: Math.max(padding, left),
      top: Math.max(padding, top),
      opacity: 1,
    });
  }, [position, cellData]);

  if (!cellData || !position) return null;

  let statusText = '';
  let statusClass = '';

  switch (cellData.status) {
    case 'collected':
      statusText = '✅ Collected & Uploaded';
      statusClass = 'text-success';
      break;
    case 'missing':
      statusText = '❌ Missing';
      statusClass = 'text-danger';
      break;
    case 'partial':
      statusText = '⚠️ Partial';
      statusClass = 'text-warning';
      break;
    case 'outside':
      statusText = 'Outside active range';
      statusClass = 'text-content-tertiary italic';
      break;
    default:
      statusText = cellData.status;
      statusClass = 'text-content-secondary';
  }

  const tooltipContent = (
    <div
      ref={tooltipRef}
      role="tooltip"
      className="fixed z-50 pointer-events-none bg-surface border border-border rounded-lg shadow-lg p-3 min-w-[200px] text-sm"
      style={style}
    >
      <div className="font-mono font-medium text-content mb-1">
        {cellData.date}
      </div>
      <div className={clsx("font-medium", statusClass)}>
        {statusText}
      </div>

      {cellData.uploadedAt && (
        <div className="mt-2 text-xs text-content-secondary">
          <span className="opacity-70">Uploaded:</span>{' '}
          <span className="font-mono">{new Date(cellData.uploadedAt).toLocaleString()}</span>
        </div>
      )}
      {cellData.sizeMb && (
        <div className="text-xs text-content-secondary mt-0.5">
          <span className="opacity-70">Size:</span>{' '}
          <span className="font-mono">{cellData.sizeMb.toFixed(2)} MB</span>
        </div>
      )}
    </div>
  );

  // Render to document.body to avoid parent z-index issues and overflow hidden
  if (typeof document !== 'undefined') {
    return createPortal(tooltipContent, document.body);
  }

  return null;
}
