// web/src/components/DateDetail.svelte
<script lang="ts">
  import PublicationCard from './PublicationCard.svelte';
  import {
    parseDjenPublicationCollectionSafely,
    fetchLivePublicationDetail,
    type DjenPublication,
  } from '../lib/djen';
  import { fetchWithRetry } from '../lib/fetchData';

  const PUBS_PER_PAGE = 1000;

  interface FeaturedPub {
    pub: DjenPublication;
    seq: number;
    page: number;
    source?: "djen" | "ia";
    usedFallback?: boolean;
  }

  function getItemId(tribunal: string, year: number): string {
    return `djen-${tribunal.toLowerCase()}-${year}`;
  }

  function getZipUrl(itemId: string, date: string, tribunal: string): string {
    return `https://archive.org/download/${itemId}/djen-${date}-${tribunal.toUpperCase()}.zip`;
  }

  function formatSize(bytes: string | number): string {
    const n = parseInt(String(bytes));
    if (isNaN(n)) return '';
    if (n > 1024 * 1024) return `${(n / (1024 * 1024)).toFixed(1)} MB`;
    if (n > 1024) return `${(n / 1024).toFixed(0)} KB`;
    return `${n} B`;
  }

  function formatRelativeTime(dateStr: string): string {
    const date = new Date(dateStr);
    const now = new Date();
    const diffMs = now.getTime() - date.getTime();
    const diffMins = Math.floor(diffMs / 60000);
    if (diffMins < 60) return `${diffMins} min atrás`;
    const diffHours = Math.floor(diffMins / 60);
    if (diffHours < 24) return `${diffHours}h atrás`;
    const diffDays = Math.floor(diffHours / 24);
    if (diffDays < 30) return `${diffDays}d atrás`;
    return date.toLocaleDateString('pt-BR');
  }

  async function cachedFetch(url: string): Promise<Response> {
    if (typeof caches !== 'undefined') {
      const cache = await caches.open('causaganha-publications');
      const cached = await cache.match(url);
      if (cached) return cached;
      const res = await fetchWithRetry(url, { redirect: 'follow' }) as Response;
      if (res.ok) cache.put(url, res.clone());
      return res;
    }
    return fetchWithRetry(url, { redirect: 'follow' }) as Promise<Response>;
  }

  interface DateDetailProps {
    tribunalCode: string;
    dateStr: string;
    initialPage?: number;
    initialSeq?: number;
  }

  let { tribunalCode, dateStr, initialPage, initialSeq }: DateDetailProps = $props();

  let totalPages = $state<number>(0);
  let currentPage = $state<number>(initialPage || 1);
  let publications = $state<DjenPublication[]>([]);
  let zipSize = $state<number | null>(null);
  let zipAddedDate = $state<string | null>(null);
  let zipMd5 = $state<string | null>(null);
  let itemFileCount = $state<number | null>(null);
  let loading = $state<boolean>(true);
  let loadingMore = $state<boolean>(false);
  let error = $state<string | null>(null);
  let featuredPub = $state<FeaturedPub | null>(null);

  let tribunal = $derived(tribunalCode.toUpperCase());
  let year = $derived(dateStr.substring(0, 4));
  let itemId = $derived(getItemId(tribunal, parseInt(year)));
  let zipUrl = $derived(getZipUrl(itemId, dateStr, tribunal));

  function jsonUrl(pageNum: number): string {
    return `${zipUrl}/${tribunal}-D-${dateStr}_${pageNum}.json`;
  }

  async function loadPage(pageNum: number): Promise<DjenPublication[] | null> {
    const res = await cachedFetch(jsonUrl(pageNum));
    if (!res.ok) return null;
    const data = await res.json();
    return parseDjenPublicationCollectionSafely(data);
  }

  $effect(() => {
    // Track reactive deps
    const _itemId = itemId;
    const _dateStr = dateStr;
    const _tribunal = tribunal;
    const _initialPage = initialPage;
    const _initialSeq = initialSeq;

    async function init() {
      loading = true;
      error = null;
      featuredPub = null;
      try {
        // ZIP metadata from IA
        const metaRes = await fetchWithRetry(`https://archive.org/metadata/${_itemId}`);
        if (metaRes.ok) {
          const meta = await metaRes.json();
          const files = meta.files || [];
          const zipName = `djen-${_dateStr}-${_tribunal}.zip`;
          const zf = files.find((f: any) => f.name === zipName);
          if (zf?.size) zipSize = parseInt(zf.size);
          if (zf?.mtime || zf?.addeddate) {
            const ts = zf.addeddate || new Date(parseInt(zf.mtime) * 1000).toISOString();
            zipAddedDate = ts;
          }
          if (zf?.md5) zipMd5 = zf.md5;
          // Count non-system data files in the item
          const dataFiles = files.filter((f: any) => !f.name.startsWith('__') && !f.name.endsWith('.xml') && !f.name.endsWith('.sqlite') && f.source !== 'metadata');
          itemFileCount = dataFiles.length;
        }

        // Probe pages
        const probes = await Promise.all(
          Array.from({ length: 30 }, (_, i) => i + 1).map(async (n) => {
            try {
              const res = await fetchWithRetry(jsonUrl(n), { method: 'HEAD', redirect: 'follow' });
              return res.ok ? n : null;
            } catch { return null; }
          })
        );
        const valid = probes.filter(Boolean) as number[];
        totalPages = valid.length;

        // Load target page
        const targetPage = _initialPage || 1;
        if (_initialSeq && targetPage <= valid.length) {
          // Deep-link to specific publication
          const pubs = await loadPage(targetPage);
          if (pubs) {
            const idx = _initialSeq - ((targetPage - 1) * PUBS_PER_PAGE) - 1;
            if (idx >= 0 && idx < pubs.length) {
              const liveData = await fetchLivePublicationDetail(pubs[idx]);
              featuredPub = {
                pub: liveData.publication || pubs[idx],
                seq: _initialSeq,
                page: targetPage,
                source: liveData.source,
                usedFallback: liveData.usedFallback
              };
            }
            publications = pubs;
            currentPage = targetPage;
          }
        } else if (valid.length > 0) {
          const pubs = await loadPage(1);
          if (pubs) publications = pubs;
          currentPage = 1;
        }
      } catch (err: unknown) {
        error = err instanceof Error ? err.message : String(err);
      } finally {
        loading = false;
      }
    }
    init();
  });

  async function handleLoadMore() {
    const next = currentPage + 1;
    if (next > totalPages) return;
    loadingMore = true;
    try {
      const pubs = await loadPage(next);
      if (pubs) {
        publications = [...publications, ...pubs];
        currentPage = next;
        history.replaceState(null, '', `#${dateStr}/${next}`);
      }
    } finally {
      loadingMore = false;
    }
  }

  function handleNavigate(newSeq: number) {
    if (newSeq < 1) return;
    const newPage = Math.ceil(newSeq / PUBS_PER_PAGE);
    const hash = `${dateStr}/${newPage}/${newSeq}`;
    history.replaceState(null, '', `#${hash}`);
    (async () => {
      let pubs = publications;
      if (newPage !== featuredPub?.page || pubs.length === 0) {
        const loaded = await loadPage(newPage);
        if (loaded) {
          pubs = loaded;
          publications = loaded;
          currentPage = newPage;
        }
      }
      const idx = newSeq - ((newPage - 1) * PUBS_PER_PAGE) - 1;
      if (idx >= 0 && idx < pubs.length) {
        const liveData = await fetchLivePublicationDetail(pubs[idx]);
        featuredPub = {
          pub: liveData.publication || pubs[idx],
          seq: newSeq,
          page: newPage,
          source: liveData.source,
          usedFallback: liveData.usedFallback
        };
      }
    })();
  }

  let shareLinkCopied = $state(false);

  function handleShareClick(e: MouseEvent) {
    e.preventDefault();
    const url = `${window.location.origin}${window.location.pathname}#${dateStr}`;
    navigator.clipboard?.writeText(url);
    shareLinkCopied = true;
    setTimeout(() => shareLinkCopied = false, 2000);
  }

  function handleDismissFeatured() {
    featuredPub = null;
    history.replaceState(null, '', `#${dateStr}`);
  }
</script>

{#snippet DateShareButton()}
  <button
    onclick={handleShareClick}
    class="btn btn-outline-secondary"
  >
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
      <path stroke-linecap="round" stroke-linejoin="round" d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101m-.758-4.899a4 4 0 005.656 0l4-4a4 4 0 00-5.656-5.656l-1.1 1.1" />
    </svg>
    {shareLinkCopied ? 'Copiado!' : 'Link'}
  </button>
{/snippet}

<div>
  {#if featuredPub}
    <div>
      <PublicationCard
        pub={featuredPub.pub}
        seq={featuredPub.seq}
        dateStr={dateStr}
        page={featuredPub.page}
        totalSeq={publications.length || totalPages * PUBS_PER_PAGE}
        onNavigate={handleNavigate}
        source={featuredPub.source}
        usedFallback={featuredPub.usedFallback}
      />
      <button
        class="btn"
        onclick={handleDismissFeatured}
      >
        Ver todas as publicações
      </button>
    </div>
  {/if}

  <!-- Date header -->
  <div class="card">
    <div class="card-body">
      <header class="header-row">
        <div class="header-info">
          <h3 class="date-title">{dateStr}</h3>
          {#if zipSize != null}
            <span class="badge-accent">{formatSize(zipSize)}</span>
          {/if}
          {#if totalPages > 0}
            <span class="meta-dim">{totalPages} pág.</span>
          {/if}
          {#if itemFileCount != null}
            <span class="meta-dim">{itemFileCount} arquivos</span>
          {/if}
        </div>
        <div class="header-actions" aria-label="Ações do arquivo">
          {@render DateShareButton()}
          <a href={zipUrl} class="btn btn-outline-secondary" target="_blank" rel="noopener noreferrer">Baixar ZIP</a>
          <a href={`https://archive.org/details/${itemId}`} class="btn btn-outline-secondary" target="_blank" rel="noopener noreferrer">Ver no IA</a>
        </div>
      </header>
      <div class="meta-row">
        {#if zipAddedDate}
          <span title={`Arquivado em ${new Date(zipAddedDate).toLocaleString('pt-BR')}`}>
            Arquivado {formatRelativeTime(zipAddedDate)}
          </span>
        {/if}
        {#if zipMd5}
          <span title={`MD5: ${zipMd5}`}>
            MD5: {zipMd5.substring(0, 8)}...
          </span>
        {/if}
      </div>
    </div>
  </div>

  {#if loading}
    <div class="loading-center"><span class="spinner spinner--lg"></span></div>
  {/if}

  {#if error}
    <div class="card"><div class="card-body error-text">Erro: {error}</div></div>
  {/if}

  {#if publications.length > 0 && !featuredPub}
    <div>
      {#each publications as pub, i (pub.id || i)}
        <PublicationCard
          pub={pub}
          seq={i + 1}
          dateStr={dateStr}
          page={Math.floor(i / PUBS_PER_PAGE) + 1}
          compact
        />
      {/each}
    </div>
  {/if}

  {#if currentPage < totalPages && !loading}
    <div class="load-more-row">
      <button onclick={handleLoadMore} disabled={loadingMore} class="btn btn--secondary" aria-busy={loadingMore}>
        {loadingMore ? 'Carregando...' : `Página ${currentPage + 1} de ${totalPages}`}
      </button>
    </div>
  {/if}

  {#if currentPage >= totalPages && publications.length > 0 && !loading && !featuredPub}
    <div class="end-summary">
      {publications.length.toLocaleString()} publicações
    </div>
  {/if}

  {#if !loading && publications.length === 0 && !error}
    <div class="card"><div class="card-body empty-text">Nenhuma publicação encontrada.</div></div>
  {/if}
</div>

<style>

  .header-row {
    display: flex;
    justify-content: space-between;
    align-items: center;
    flex-wrap: wrap;
    gap: 1rem;
  }

  .header-info {
    display: flex;
    align-items: center;
    gap: 1.5rem;
    flex-wrap: wrap;
  }

  .date-title {
    margin: 0;
  }

  .badge-accent {
    display: inline-flex;
    align-items: center;
    padding: 0.125rem 0.5rem;
    font-size: var(--font-size-xs);
    font-weight: 500;
    border-radius: var(--radius-full);
    background: var(--color-accent);
    color: var(--color-accent-content);
  }

  .meta-dim {
    opacity: 0.5;
    font-size: var(--font-size-sm);
  }

  .header-actions {
    display: flex;
    gap: 0.5rem;
  }

  .meta-row {
    display: flex;
    gap: 1.5rem;
    font-size: var(--font-size-xs);
    opacity: 0.5;
    margin-top: 1rem;
  }

  .loading-center {
    display: flex;
    justify-content: center;
    padding: 2rem;
  }

  .spinner {
    border: 2px solid var(--color-base-300);
    border-top-color: var(--color-primary);
    border-radius: 50%;
    animation: spin 0.6s linear infinite;
  }

  .spinner--lg {
    width: 2rem;
    height: 2rem;
  }

  @keyframes spin {
    to { transform: rotate(360deg); }
  }

  .error-text {
    color: var(--color-error);
    text-align: center;
  }

  .empty-text {
    text-align: center;
    opacity: 0.5;
  }

  .btn--secondary {
    background: var(--color-secondary);
    color: var(--color-secondary-content);
  }

  .load-more-row {
    text-align: center;
    margin-top: 4rem;
  }

  .end-summary {
    text-align: center;
    margin-top: 4rem;
    opacity: 0.5;
    font-size: var(--font-size-sm);
  }
</style>

// dashboard/src/components/DateDetail.tsx
import { useState, useEffect, useCallback } from 'preact/compat';
import { PublicationCard } from './PublicationCard';

const PUBS_PER_PAGE = 1000;

interface Publication {
  id?: string;
  numero_processo?: string;
  tipoComunicacao?: string;
  nomeOrgao?: string;
  texto?: string;
  destinatarios?: { nome: string }[];
  destinatarioadvogados?: { advogado?: { nome?: string; numero_oab?: string; uf_oab?: string } }[];
}

interface FeaturedPub {
  pub: Publication;
  seq: number;
  page: number;
}

function getItemId(tribunal: string, year: number): string {
  return `djen-${tribunal.toLowerCase()}-${year}`;
}

function getZipUrl(itemId: string, date: string, tribunal: string): string {
  return `https://archive.org/download/${itemId}/djen-${date}-${tribunal.toUpperCase()}.zip`;
}

function formatSize(bytes: string | number): string {
  const n = parseInt(String(bytes));
  if (isNaN(n)) return '';
  if (n> 1024 * 1024) return `${(n / (1024 * 1024)).toFixed(1)} MB`;
  if (n> 1024) return `${(n / 1024).toFixed(0)} KB`;
  return `${n} B`;
}

function formatRelativeTime(dateStr: string): string {
  const date = new Date(dateStr);
  const now = new Date();
  const diffMs = now.getTime() - date.getTime();
  const diffMins = Math.floor(diffMs / 60000);
  if (diffMins < 60) return `${diffMins} min atrás`;
  const diffHours = Math.floor(diffMins / 60);
  if (diffHours < 24) return `${diffHours}h atrás`;
  const diffDays = Math.floor(diffHours / 24);
  if (diffDays < 30) return `${diffDays}d atrás`;
  return date.toLocaleDateString('pt-BR');
}

function DateShareButton({ dateStr }: { dateStr: string }) {
  const [copied, setCopied] = useState(false);
  const handleClick = (e: MouseEvent) => {
    e.preventDefault();
    const url = `${window.location.origin}${window.location.pathname}#${dateStr}`;
    navigator.clipboard?.writeText(url);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };
  return (
    <button onClick={handleClick} className="btn btn-outline btn-secondary" style={{ fontSize: 'var(--font-size-xs)', padding: '0.4rem 0.75rem', display: 'inline-flex', alignItems: 'center', gap: '0.35rem' }}>
      <svg  xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101m-.758-4.899a4 4 0 005.656 0l4-4a4 4 0 00-5.656-5.656l-1.1 1.1" />
      </svg>
      {copied ? 'Copiado!' : 'Link'}
    </button>
  );
}

async function cachedFetch(url: string): Promise<Response> {
  if (typeof caches !== 'undefined') {
    const cache = await caches.open('causaganha-publications');
    const cached = await cache.match(url);
    if (cached) return cached;
    const res = await fetch(url, { redirect: 'follow' });
    if (res.ok) cache.put(url, res.clone());
    return res;
  }
  return fetch(url, { redirect: 'follow' });
}

interface DateDetailProps {
  tribunalCode: string;
  dateStr: string;
  initialPage?: number;
  initialSeq?: number;
}

export function DateDetail({ tribunalCode, dateStr, initialPage, initialSeq }: DateDetailProps) {
  const [totalPages, setTotalPages] = useState<number>(0);
  const [currentPage, setCurrentPage] = useState<number>(initialPage || 1);
  const [publications, setPublications] = useState<Publication[]>([]);
  const [zipSize, setZipSize] = useState<number | null>(null);
  const [zipAddedDate, setZipAddedDate] = useState<string | null>(null);
  const [zipMd5, setZipMd5] = useState<string | null>(null);
  const [itemFileCount, setItemFileCount] = useState<number | null>(null);
  const [loading, setLoading] = useState<boolean>(true);
  const [loadingMore, setLoadingMore] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const [featuredPub, setFeaturedPub] = useState<FeaturedPub | null>(null);

  const tribunal = tribunalCode.toUpperCase();
  const year = dateStr.substring(0, 4);
  const itemId = getItemId(tribunal, parseInt(year));
  const zipUrl = getZipUrl(itemId, dateStr, tribunal);

  const jsonUrl = useCallback((pageNum: number): string => {
    return `${zipUrl}/${tribunal}-D-${dateStr}_${pageNum}.json`;
  }, [zipUrl, tribunal, dateStr]);

  const loadPage = useCallback(async (pageNum: number): Promise<Publication[] | null> => {
    const res = await cachedFetch(jsonUrl(pageNum));
    if (!res.ok) return null;
    const data = await res.json();
    return Array.isArray(data) ? data : (data.items || []);
  }, [jsonUrl]);

  useEffect(() => {
    async function init() {
      setLoading(true);
      setError(null);
      setFeaturedPub(null);
      try {
        // ZIP metadata from IA
        const metaRes = await fetch(`https://archive.org/metadata/${itemId}`);
        if (metaRes.ok) {
          const meta = await metaRes.json();
          const files = meta.files || [];
          const zipName = `djen-${dateStr}-${tribunal}.zip`;
          const zf = files.find((f: any) => f.name === zipName);
          if (zf?.size) setZipSize(parseInt(zf.size));
          if (zf?.mtime || zf?.addeddate) {
            const ts = zf.addeddate || new Date(parseInt(zf.mtime) * 1000).toISOString();
            setZipAddedDate(ts);
          }
          if (zf?.md5) setZipMd5(zf.md5);
          // Count non-system data files in the item
          const dataFiles = files.filter((f: any) => !f.name.startsWith('__') && !f.name.endsWith('.xml') && !f.name.endsWith('.sqlite') && f.source !== 'metadata');
          setItemFileCount(dataFiles.length);
        }

        // Probe pages
        const probes = await Promise.all(
          Array.from({ length: 30 }, (_, i) => i + 1).map(async (n) => {
            try {
              const res = await fetch(jsonUrl(n), { method: 'HEAD', redirect: 'follow' });
              return res.ok ? n : null;
            } catch { return null; }
          })
        );
        const valid = probes.filter(Boolean) as number[];
        setTotalPages(valid.length);

        // Load target page
        const targetPage = initialPage || 1;
        if (initialSeq && targetPage <= valid.length) {
          // Deep-link to specific publication
          const pubs = await loadPage(targetPage);
          if (pubs) {
            const idx = initialSeq - ((targetPage - 1) * PUBS_PER_PAGE) - 1;
            if (idx>= 0 && idx < pubs.length) {
              setFeaturedPub({ pub: pubs[idx], seq: initialSeq, page: targetPage });
            }
            setPublications(pubs);
            setCurrentPage(targetPage);
          }
        } else if (valid.length> 0) {
          const pubs = await loadPage(1);
          if (pubs) setPublications(pubs);
          setCurrentPage(1);
        }
      } catch (err: unknown) {
        setError(err instanceof Error ? err.message : String(err));
      } finally {
        setLoading(false);
      }
    }
    init();
  }, [itemId, dateStr, tribunal, initialPage, initialSeq, jsonUrl, loadPage]);

  const handleLoadMore = async () => {
    const next = currentPage + 1;
    if (next> totalPages) return;
    setLoadingMore(true);
    try {
      const pubs = await loadPage(next);
      if (pubs) {
        setPublications(prev => [...prev, ...pubs]);
        setCurrentPage(next);
        history.replaceState(null, '', `#${dateStr}/${next}`);
      }
    } finally {
      setLoadingMore(false);
    }
  };

  return (
    <div>
      {/* Featured publication (deep-link) */}
      {featuredPub && (
        <div>
          <PublicationCard
            pub={featuredPub.pub} seq={featuredPub.seq}
            dateStr={dateStr}
            page={featuredPub.page}
            totalSeq={publications.length || totalPages * PUBS_PER_PAGE}
            onNavigate={(newSeq: number) => {
              if (newSeq < 1) return;
              const newPage = Math.ceil(newSeq / PUBS_PER_PAGE);
              const hash = `${dateStr}/${newPage}/${newSeq}`;
              history.replaceState(null, '', `#${hash}`);
              // Load the page if needed and update featured
              (async () => {
                let pubs = publications;
                if (newPage !== featuredPub.page || pubs.length === 0) {
                  const loaded = await loadPage(newPage);
                  if (loaded) {
                    pubs = loaded;
                    setPublications(loaded);
                    setCurrentPage(newPage);
                  }
                }
                const idx = newSeq - ((newPage - 1) * PUBS_PER_PAGE) - 1;
                if (idx>= 0 && idx < pubs.length) {
                  setFeaturedPub({ pub: pubs[idx], seq: newSeq, page: newPage });
                }
              })();
            }}
          />
          <button
            className="btn"
           onClick={() => { setFeaturedPub(null); history.replaceState(null, '', `#${dateStr}`); }}>
            Ver todas as publicações
          </button>
        </div>
      )}

      {/* Date header */}
      <div className="card bg-base-100 shadow-sm border border-base-300" style={{ marginBottom: 'var(--space-lg)' }}><div className="card-body" style={{ padding: 'var(--space-md)' }}>
        <header style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 'var(--space-sm)' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-md)', flexWrap: 'wrap' }}>
            <h3 style={{ margin: 0 }}>{dateStr}</h3>
            {zipSize != null && <span className="badge badge-accent">{formatSize(zipSize)}</span>}
            {totalPages> 0 && <span className="opacity-50" style={{ fontSize: 'var(--font-size-sm)' }}>{totalPages} pág.</span>}
            {itemFileCount != null && (
              <span className="opacity-50" style={{ fontSize: 'var(--font-size-sm)' }}>{itemFileCount} arquivos</span>
            )}
          </div>
          <div className="flex gap-2" aria-label="Ações do arquivo">
            <DateShareButton dateStr={dateStr} />
            <a href={zipUrl} className="btn btn-outline btn-secondary" target="_blank" rel="noopener noreferrer" style={{ fontSize: 'var(--font-size-xs)', padding: '0.4rem 0.75rem' }}>Baixar ZIP</a>
            <a href={`https://archive.org/details/${itemId}`} className="btn btn-outline btn-secondary" target="_blank" rel="noopener noreferrer" style={{ fontSize: 'var(--font-size-xs)', padding: '0.4rem 0.75rem' }}>Ver no IA</a>
          </div>
        </header>
        <div style={{ display: 'flex', gap: 'var(--space-md)', fontSize: 'var(--font-size-xs)', color: 'var(--color-content-tertiary)', marginTop: 'var(--space-sm)' }}>
          {zipAddedDate && (
            <span title={`Arquivado em ${new Date(zipAddedDate).toLocaleString('pt-BR')}`}>
              Arquivado {formatRelativeTime(zipAddedDate)}
            </span>
          )}
          {zipMd5 && (
            <span title={`MD5: ${zipMd5}`}>
              MD5: {zipMd5.substring(0, 8)}...
            </span>
          )}
        </div>
      </div></div>

      {loading && <div className="flex justify-center p-8"><span className="loading loading-spinner loading-lg"></span></div>}
      {error && <div className="card bg-base-100 shadow-sm border border-base-300"><div className="card-body text-error text-center">Erro: {error}</div></div>}

      {/* Publications list */}
      {publications.length> 0 && !featuredPub && (
        <div>
          {publications.map((pub, i) => (
            <PublicationCard
              key={pub.id || i} pub={pub}
              seq={i + 1}
              dateStr={dateStr}
              page={Math.floor(i / PUBS_PER_PAGE) + 1}
              compact
            />
          ))}
        </div>
      )}

      {currentPage < totalPages && !loading && (
        <div className="text-center mt-16">
          <button onClick={handleLoadMore} disabled={loadingMore} className="btn btn-secondary" aria-busy={loadingMore}>
            {loadingMore ? 'Carregando...' : `Página ${currentPage + 1} de ${totalPages}`}
          </button>
        </div>
      )}

      {currentPage>= totalPages && publications.length> 0 && !loading && !featuredPub && (
        <div style={{ textAlign: 'center', marginTop: 'var(--space-xl)', color: 'var(--color-content-tertiary)', fontSize: 'var(--font-size-sm)' }}>
          {publications.length.toLocaleString()} publicações
        </div>
      )}

      {!loading && publications.length === 0 && !error && (
        <div className="card bg-base-100 shadow-sm border border-base-300"><div className="card-body text-center opacity-50">Nenhuma publicação encontrada.</div></div>
      )}
    </div>
  );
}
