// web/src/components/Heatmap.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { fade } from 'svelte/transition';
  import CellTooltip from './CellTooltip.svelte';
  import VelocityTimeline from './VelocityTimeline.svelte';
  import { type CellStatus, CELL_STATUS_COLORS } from '../lib/colorUtils';
  import { toDateString } from '../lib/dateUtils';

  interface CellData {
    date: string;
    status: string;
    uploadedAt: string | null;
    sizeMb: number | null;
  }

  interface HoveredCellState {
    data: CellData;
    position: { x: number; y: number };
  }

  interface HeatmapProps {
    globalStartDateStr: string;
    globalEndDateStr: string;
    tribunalStartDateStr: string | null;
    coverageSet: Set<string>;
    tribunalName: string;
    baseUrl: string | null;
    velocityMetrics: any;
  }

  let {
    globalStartDateStr,
    globalEndDateStr,
    tribunalStartDateStr,
    coverageSet,
    tribunalName,
    baseUrl,
    velocityMetrics
  }: HeatmapProps = $props();

  let hoveredCell = $state<HoveredCellState | null>(null);
  let focusedCell = $state<string | null>(null);

  function handleOutsideInteraction() { hoveredCell = null; }

  onMount(() => {
    document.addEventListener('touchstart', handleOutsideInteraction, { passive: true });
    document.addEventListener('click', handleOutsideInteraction, { passive: true });
  });

  onDestroy(() => {
    if (typeof document !== 'undefined') {
      document.removeEventListener('touchstart', handleOutsideInteraction);
      document.removeEventListener('click', handleOutsideInteraction);
    }
  });

  let start = $derived(new Date(globalStartDateStr + 'T00:00:00Z'));
  let end   = $derived(new Date(globalEndDateStr   + 'T00:00:00Z'));
  let invalidRange = $derived(start > end);

  // ── Year/month picker state ──────────────────────────────────────────────
  const _now = new Date();
  let selectedYear  = $state(_now.getUTCFullYear());
  let selectedMonth = $state(_now.getUTCMonth()); // 0-indexed

  let minYear = $derived(start.getUTCFullYear());
  let maxYear = $derived(end.getUTCFullYear());

  // Clamp year to valid range when props change
  $effect(() => {
    if (selectedYear < minYear) { selectedYear = minYear; }
    if (selectedYear > maxYear) { selectedYear = maxYear; }
  });

  // Reset focused cell when navigation changes
  $effect(() => {
    selectedYear; selectedMonth;
    focusedCell = null;
  });

  function prevYear() { if (selectedYear > minYear) selectedYear--; }
  function nextYear() { if (selectedYear < maxYear) selectedYear++; }
  function goToToday() {
    const now = new Date();
    selectedYear = now.getUTCFullYear();
    selectedMonth = now.getUTCMonth();
  }

  function selectMonth(mo: number) {
    const first = new Date(Date.UTC(selectedYear, mo, 1));
    const last  = new Date(Date.UTC(selectedYear, mo + 1, 0));
    if (first > end || last < start) return; // outside data range
    selectedMonth = mo;
  }

  // ── Month-picker coverage badges ────────────────────────────────────────
  const MONTH_NAMES = ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'];

  let monthCoverage = $derived.by(() =>
    MONTH_NAMES.map((name, mo) => {
      const first = new Date(Date.UTC(selectedYear, mo, 1));
      const last  = new Date(Date.UTC(selectedYear, mo + 1, 0));
      if (first > end || last < start) return { name, mo, total: 0, collected: 0, pct: -1 };

      let total = 0, collected = 0;
      for (let d = 1; d <= last.getUTCDate(); d++) {
        const dt = new Date(Date.UTC(selectedYear, mo, d));
        if (dt < start || dt > end) continue;
        const ds = toDateString(dt);
        if (tribunalStartDateStr && ds < tribunalStartDateStr) continue;
        total++;
        if (coverageSet.has(ds)) collected++;
      }
      return { name, mo, total, collected, pct: total > 0 ? collected / total : 0 };
    })
  );

  function monthBadgeClass(pct: number): string {
    if (pct < 0)    return 'month-outside';
    if (pct >= 0.8) return 'month-high';
    if (pct >= 0.5) return 'month-mid';
    if (pct > 0)    return 'month-low';
    return 'month-zero';
  }

  // ── Single-month calendar ────────────────────────────────────────────────
  let selectedMonthCalendar = $derived.by(() => {
    const yr = selectedYear, mo = selectedMonth;
    const firstDay = new Date(Date.UTC(yr, mo, 1));
    const lastDay  = new Date(Date.UTC(yr, mo + 1, 0));
    const startDow = firstDay.getUTCDay();

    const weeks: (string | null)[][] = [];
    let week: (string | null)[] = Array(startDow).fill(null);

    for (let d = 1; d <= lastDay.getUTCDate(); d++) {
      const dt = new Date(Date.UTC(yr, mo, d));
      week.push((dt >= start && dt <= end) ? toDateString(dt) : null);
      if (week.length === 7) { weeks.push(week); week = []; }
    }
    if (week.length > 0) {
      while (week.length < 7) week.push(null);
      weeks.push(week);
    }

    const label = firstDay.toLocaleString('pt-BR', { month: 'long', year: 'numeric', timeZone: 'UTC' });
    return { label, weeks };
  });

  let allDays     = $derived(selectedMonthCalendar.weeks.flat().filter(Boolean) as string[]);
  let coveredDays = $derived(allDays.filter(d => coverageSet.has(d)).length);
  let totalDays   = $derived(allDays.length);

  // ── Cell helpers (unchanged logic) ──────────────────────────────────────
  function getCellStatus(dateStr: string): CellStatus {
    if (tribunalStartDateStr && dateStr < tribunalStartDateStr) return 'outside';
    if (coverageSet.has(dateStr)) return 'collected';
    if (velocityMetrics?.absentSet?.has(dateStr)) return 'absent';
    return 'missing';
  }

  function getCellColor(dateStr: string | null): string {
    if (!dateStr) return '';
    const status = getCellStatus(dateStr);
    const base = CELL_STATUS_COLORS[status];
    return focusedCell === dateStr ? `${base} heatmap-focused heatmap-cell` : `${base} heatmap-cell`;
  }

  function getAriaLabel(dateStr: string | null): string {
    if (!dateStr) return 'Empty cell';
    const status = getCellStatus(dateStr);
    if (status === 'outside')  return `${dateStr}: Before Tribunal Joined`;
    if (status === 'absent')   return `${dateStr}: Confirmed Absent (No journal published)`;
    return `${dateStr}: ${status === 'collected' ? 'Collected' : 'Missing'}`;
  }

  function handleCellInteraction(e: any, dateStr: string | null, type: string) {
    if (e?.stopPropagation) e.stopPropagation();
    if (!dateStr) return;
    if (type === 'leave') { hoveredCell = null; return; }
    if (type === 'touch') {
      if (e?.cancelable) e.preventDefault();
      const pos = { x: e.touches[0].clientX, y: e.touches[0].clientY };
      hoveredCell = hoveredCell?.data?.date === dateStr ? null
        : { data: { date: dateStr, status: getCellStatus(dateStr), uploadedAt: null, sizeMb: null }, position: pos };
      return;
    }
    const pos = { x: e.clientX, y: e.clientY };
    if (type === 'click') {
      if (getCellStatus(dateStr) === 'collected' && baseUrl) { window.location.hash = dateStr; return; }
      if (hoveredCell?.data?.date === dateStr) { hoveredCell = null; return; }
    }
    hoveredCell = { data: { date: dateStr, status: getCellStatus(dateStr), uploadedAt: null, sizeMb: null }, position: pos };
  }

  function handleGridKeyDown(e: any) {
    if (!allDays.length) return;
    let idx = focusedCell ? allDays.indexOf(focusedCell) : allDays.length - 1;
    if (idx === -1) idx = allDays.length - 1;
    let next = idx;
    switch (e.key) {
      case 'ArrowLeft':  next = Math.max(0, idx - 1);              e.preventDefault(); break;
      case 'ArrowRight': next = Math.min(allDays.length - 1, idx + 1); e.preventDefault(); break;
      case 'ArrowUp':    next = Math.max(0, idx - 7);              e.preventDefault(); break;
      case 'ArrowDown':  next = Math.min(allDays.length - 1, idx + 7); e.preventDefault(); break;
      case 'Enter': case ' ':
        if (focusedCell) {
          e.preventDefault();
          const rect = document.getElementById(`cell-${focusedCell}`)?.getBoundingClientRect()
            ?? { x: window.innerWidth / 2, y: window.innerHeight / 2 };
          handleCellInteraction({ clientX: rect.x + 6, clientY: rect.y + 6, stopPropagation: () => {} }, focusedCell, 'click');
        }
        break;
      case 'Escape': hoveredCell = null; e.preventDefault(); break;
      default: return;
    }
    if (next !== idx && allDays[next]) focusedCell = allDays[next];
  }

  const weekdayHeaders = ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'];
</script>

{#if invalidRange}
  <div>Invalid date range.</div>
{:else}
  <div class="heatmap-wrapper">

    <!-- ── Year wheel ──────────────────────────────────────── -->
    <div class="year-nav">
      <button
        class="year-arrow"
        onclick={prevYear}
        disabled={selectedYear <= minYear}
        aria-label="Ano anterior"
      >&#8592;</button>
      <span class="year-label">{selectedYear}</span>
      <button
        class="year-arrow"
        onclick={nextYear}
        disabled={selectedYear >= maxYear}
        aria-label="Próximo ano"
      >&#8594;</button>
      <button class="today-btn" onclick={goToToday} aria-label="Ir para o mês atual">
        Hoje
      </button>
    </div>

    <!-- ── Month picker grid ───────────────────────────────── -->
    <div class="month-picker" role="listbox" aria-label="Selecionar mês">
      {#each monthCoverage as mc}
        {@const isSelected = mc.mo === selectedMonth}
        {@const isDisabled = mc.pct < 0}
        <button
          class="month-btn {monthBadgeClass(mc.pct)} {isSelected ? 'month-selected' : ''}"
          onclick={() => selectMonth(mc.mo)}
          disabled={isDisabled}
          role="option"
          aria-selected={isSelected}
          aria-label="{mc.name}: {mc.pct >= 0 ? Math.round(mc.pct * 100) + '% coletado' : 'fora do intervalo'}"
          title="{mc.collected}/{mc.total} dias coletados"
        >
          <span class="month-name">{mc.name}</span>
          {#if mc.pct >= 0 && mc.total > 0}
            <div class="month-progress">
              <div class="month-progress-fill" style="width:{Math.round(mc.pct * 100)}%"></div>
            </div>
          {/if}
        </button>
      {/each}
    </div>

    <!-- ── Single-month calendar ───────────────────────────── -->
    {#key `${selectedYear}-${selectedMonth}`}
    <div class="month-card" transition:fade={{ duration: 120 }}>
      <h5 class="month-title">{selectedMonthCalendar.label}</h5>
      <table
        class="calendar-table"
        role="grid"
        aria-label="Calendário de cobertura — {selectedMonthCalendar.label} — {tribunalName}"
        tabindex="0"
        onkeydown={handleGridKeyDown}
        onfocus={() => { if (!focusedCell) focusedCell = allDays[allDays.length - 1]; }}
        onblur={() => { focusedCell = null; hoveredCell = null; }}
      >
        <thead>
          <tr>
            {#each weekdayHeaders as d}
              <th class="weekday-header">{d}</th>
            {/each}
          </tr>
        </thead>
        <tbody>
          {#each selectedMonthCalendar.weeks as week, wi}
            <tr>
              {#each week as day, di}
                <td
                  id={day ? `cell-${day}` : undefined}
                  role="gridcell"
                  class="day-cell {day ? `day-cell--active ${getCellColor(day)} ${day && getCellStatus(day) === 'collected' && baseUrl ? 'day-cell--clickable' : 'day-cell--default'}` : ''}"
                  aria-label={getAriaLabel(day)}
                  aria-selected={focusedCell === day}
                  onmouseenter={(e: any) => handleCellInteraction(e, day, 'enter')}
                  onmousemove={(e: any)  => handleCellInteraction(e, day, 'move')}
                  onmouseleave={(e: any) => handleCellInteraction(e, day, 'leave')}
                  ontouchstart={(e: any) => handleCellInteraction(e, day, 'touch')}
                  onclick={(e: any) => { handleCellInteraction(e, day, 'click'); focusedCell = day; }}
                >
                  {day ? new Date(day + 'T00:00:00Z').getUTCDate() : ''}
                </td>
              {/each}
            </tr>
          {/each}
        </tbody>
      </table>
    </div>
    {/key}

    <!-- ── Legend ──────────────────────────────────────────── -->
    <div class="legend-card">
      <div class="legend-body">
        <span class="legend-summary">
          <strong>{coveredDays}</strong> de <strong>{totalDays}</strong> dias com dados neste mês
        </span>
        <div class="legend-items">
          <span class="legend-label">Legenda:</span>
          <div class="legend-item"><div class="legend-swatch heatmap-missing"></div><span>Faltante</span></div>
          <div class="legend-item"><div class="legend-swatch heatmap-absent"></div><span>Ausente</span></div>
          <div class="legend-item"><div class="legend-swatch heatmap-collected"></div><span>Coletado</span></div>
        </div>
      </div>
    </div>

    {#if velocityMetrics?.hasEnoughHistory}
      <div class="velocity-section">
        <VelocityTimeline metrics={velocityMetrics} />
      </div>
    {/if}

    {#if hoveredCell}
      <CellTooltip cellData={hoveredCell.data} position={hoveredCell.position} />
    {/if}

  </div>
{/if}

<style>
  .heatmap-wrapper {
    display: flex;
    flex-direction: column;
    gap: 1.25rem;
  }

  /* ── Year navigation ── */
  .year-nav {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 1rem;
  }

  .year-arrow {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 2rem;
    height: 2rem;
    border-radius: var(--radius-full);
    border: 1px solid var(--color-base-300);
    background: transparent;
    cursor: pointer;
    font-size: 1rem;
    line-height: 1;
    transition: background 0.15s;
  }

  .year-arrow:hover:not(:disabled) {
    background: var(--color-base-200);
  }

  .year-arrow:disabled {
    opacity: 0.3;
    cursor: default;
  }

  .year-label {
    font-size: var(--font-size-xl, 1.25rem);
    font-weight: 700;
    min-width: 4rem;
    text-align: center;
  }

  .today-btn {
    font-size: var(--font-size-xs);
    padding: 0.25rem 0.625rem;
    border-radius: var(--radius-full);
    border: 1px solid var(--color-base-300);
    background: transparent;
    cursor: pointer;
    opacity: 0.7;
    transition: opacity 0.15s, background 0.15s;
  }

  .today-btn:hover {
    opacity: 1;
    background: var(--color-base-200);
  }

  /* ── Month picker ── */
  .month-picker {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(4rem, 1fr));
    gap: 0.375rem;
  }

  .month-btn {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 0.25rem;
    padding: 0.5rem 0.25rem 0.375rem;
    border-radius: var(--radius-box);
    border: 2px solid transparent;
    background: var(--color-base-200);
    cursor: pointer;
    transition: border-color 0.15s, background 0.15s;
    position: relative;
    overflow: hidden;
  }

  .month-btn:disabled {
    opacity: 0.35;
    cursor: default;
  }

  .month-btn:not(:disabled):hover {
    border-color: var(--color-primary);
  }

  .month-selected {
    border-color: var(--color-primary) !important;
    background: color-mix(in srgb, var(--color-primary) 10%, var(--color-base-100));
  }

  .month-name {
    font-size: var(--font-size-xs);
    font-weight: 600;
    line-height: 1;
  }

  /* ── Month coverage mini-bar ── */
  .month-progress {
    width: 100%;
    height: 3px;
    background: var(--color-base-300);
    border-radius: 2px;
    overflow: hidden;
  }

  .month-progress-fill {
    height: 100%;
    border-radius: 2px;
    transition: width 0.3s;
  }

  .month-high   .month-progress-fill { background: var(--color-success); }
  .month-mid    .month-progress-fill { background: var(--color-warning); }
  .month-low    .month-progress-fill { background: var(--color-error);   }
  .month-zero   .month-progress-fill { background: var(--color-base-300); }
  .month-outside { opacity: 0.3; }

  /* ── Single month calendar ── */
  .month-card {
    background: var(--color-base-100);
    border: 1px solid var(--color-base-300);
    border-radius: var(--radius-box);
    padding: 1rem;
  }

  .month-title {
    font-size: var(--font-size-sm);
    font-weight: 600;
    text-transform: capitalize;
    margin-bottom: 0.75rem;
    text-align: center;
  }

  .calendar-table {
    width: 100%;
    max-width: 22rem;
    margin: 0 auto;
  }

  .weekday-header {
    font-size: var(--font-size-xs);
    opacity: 0.5;
    font-weight: 400;
    text-align: center;
    padding-bottom: 0.25rem;
  }

  .day-cell {
    text-align: center;
    font-size: var(--font-size-xs);
    padding: 0.2rem;
  }

  .day-cell--active   { border-radius: var(--radius-sm); }
  .day-cell--clickable { cursor: pointer; }
  .day-cell--default  { cursor: default; }

  /* ── Legend ── */
  .legend-card   { background: var(--color-base-200); border-radius: var(--radius-box); }

  .legend-body {
    padding: 0.75rem 1rem;
    display: flex;
    flex-direction: row;
    justify-content: space-between;
    align-items: center;
    font-size: var(--font-size-sm);
    flex-wrap: wrap;
    gap: 0.75rem;
  }

  .legend-summary { opacity: 0.7; }

  .legend-items {
    display: flex;
    align-items: center;
    flex-wrap: wrap;
    gap: 1rem;
  }

  .legend-label { opacity: 0.5; }

  .legend-item  { display: flex; align-items: center; gap: 0.375rem; }

  .legend-swatch {
    width: 0.75rem;
    height: 0.75rem;
    border-radius: var(--radius-sm);
  }

  /* ── Velocity section ── */
  .velocity-section {
    border-top: 1px solid var(--color-base-300);
    padding-top: 1.5rem;
    margin-top: 1rem;
  }
</style>

// dashboard/src/components/Heatmap.tsx
import { useState, useEffect } from 'preact/compat';
import { CellTooltip } from './CellTooltip';
import { CellStatus, CELL_STATUS_COLORS, getBarColor } from '../lib/colorUtils';
import { toDateString } from '../lib/dateUtils';

interface VelocityWeek {
  collected: number;
  weekOffset: number;
}

interface VelocityTimelineProps {
  metrics: any;
}

export function VelocityTimeline({ metrics }: VelocityTimelineProps) {
  if (!metrics || !metrics.hasEnoughHistory) return null;

  const { weeklyData, historicalAvgVelocity, currentVelocity, trend } = metrics;
  const maxCollected = Math.max(7, ...weeklyData.map((w: VelocityWeek) => w.collected));

  let trendColor = "opacity-50";
  let trendText = "Estável";
  if (currentVelocity > historicalAvgVelocity * 1.2) {
    trendColor = "text-success";
    trendText = "Acelerando";
  } else if (currentVelocity < historicalAvgVelocity * 0.7) {
    trendColor = "text-error";
    trendText = "Em declínio";
  }

  return (
    <div aria-label="Velocidade de Coleta nas Últimas 12 Semanas">
      <div className="flex justify-between items-baseline flex-wrap gap-4 mb-6 items-baseline">
        <div>
          <h4 className="mb-0">Velocidade de Coleta</h4>
          <p className="opacity-50 mb-0 text-sm">Taxa de coleta das últimas 12 semanas</p>
        </div>
        <div className="text-right">
          <div className="font-bold">{currentVelocity.toFixed(1)} dias/sem (média)</div>
          <div className={`${trendColor} text-sm`}>
            {trend > 0 ? '+' : ''}{trend.toFixed(0)}% vs média ({trendText})
          </div>
        </div>
      </div>

      <div role="list" className="flex items-end mt-10 gap-1 h-[100px]">
        {weeklyData.map((week: VelocityWeek, idx: number) => {
          const heightPct = Math.max(5, (week.collected / maxCollected) * 100);

          return (
            <div
              key={`w-${idx}`}
              role="listitem"
              className="flex items-end flex-1 relative h-full"
              title={`${week.collected} dias coletados (Semana ${12 - week.weekOffset})`}
              aria-label={`${week.collected} dias coletados na semana ${12 - week.weekOffset}`}>
              <div
                className={`${getBarColor(week.collected)} w-full rounded-t opacity-80 transition-opacity`}
                style={{ height: `${heightPct}%` }}></div>
            </div>
          );
        })}
      </div>

      <div className="flex justify-between items-baseline opacity-50 mt-2 text-xs">
        <span>12 semanas atrás</span>
        <span>Atual</span>
      </div>
    </div>
  );
}

interface HeatmapProps {
  globalStartDateStr: string;
  globalEndDateStr: string;
  tribunalStartDateStr: string | null;
  coverageSet: Set<string>;
  tribunalName: string;
  baseUrl: string | null;
  velocityMetrics: any;
}

interface CellData {
  date: string;
  status: string;
  uploadedAt: string | null;
  sizeMb: number | null;
}

interface HoveredCellState {
  data: CellData;
  position: { x: number; y: number };
}

export function Heatmap({ globalStartDateStr, globalEndDateStr, tribunalStartDateStr, coverageSet, tribunalName, baseUrl, velocityMetrics }: HeatmapProps) {
  const [hoveredCell, setHoveredCell] = useState<HoveredCellState | null>(null);
  const [focusedCell, setFocusedCell] = useState<string | null>(null);

  useEffect(() => {
    const handleOutsideInteraction = () => setHoveredCell(null);
    if (typeof document !== 'undefined') {
      document.addEventListener('touchstart', handleOutsideInteraction, { passive: true });
      document.addEventListener('click', handleOutsideInteraction, { passive: true });
    }
    return () => {
      if (typeof document !== 'undefined') {
        document.removeEventListener('touchstart', handleOutsideInteraction);
        document.removeEventListener('click', handleOutsideInteraction);
      }
    };
  }, []);

  const start = new Date(globalStartDateStr + "T00:00:00Z");
  const end = new Date(globalEndDateStr + "T00:00:00Z");

  if (start> end) {
    return <div>Invalid date range.</div>;
  }

  // Build months for calendar view
  const months: { year: number; month: number; label: string; weeks: (string | null)[][] }[] = [];
  const cursor = new Date(Date.UTC(start.getUTCFullYear(), start.getUTCMonth(), 1));
  const endMonth = new Date(Date.UTC(end.getUTCFullYear(), end.getUTCMonth(), 1));

  while (cursor <= endMonth) {
    const yr = cursor.getUTCFullYear();
    const mo = cursor.getUTCMonth();
    const firstDay = new Date(Date.UTC(yr, mo, 1));
    const lastDay = new Date(Date.UTC(yr, mo + 1, 0));
    const startDow = firstDay.getUTCDay(); // 0=Sun

    const weeks: (string | null)[][] = [];
    let week: (string | null)[] = Array(startDow).fill(null);

    for (let d = 1; d <= lastDay.getUTCDate(); d++) {
      const dt = new Date(Date.UTC(yr, mo, d));
      const ds = toDateString(dt);
      // Only include days within the global range
      if (dt >= start && dt <= end) {
        week.push(ds);
      } else {
        week.push(null);
      }
      if (week.length === 7) {
        weeks.push(week);
        week = [];
      }
    }
    if (week.length > 0) {
      while (week.length < 7) week.push(null);
      weeks.push(week);
    }

    const label = firstDay.toLocaleString('pt-BR', { month: 'long', year: 'numeric', timeZone: 'UTC' });
    months.push({ year: yr, month: mo, label, weeks });
    cursor.setUTCMonth(cursor.getUTCMonth() + 1);
  }

  const allDays = months.flatMap(m => m.weeks.flat().filter(Boolean) as string[]);
  const coveredDays = allDays.filter(d => coverageSet.has(d)).length;
  const totalDays = allDays.length;

  const getCellStatus = (dateStr: string): CellStatus => {
    if (tribunalStartDateStr && dateStr < tribunalStartDateStr) {
      return 'outside';
    }
    if (coverageSet.has(dateStr)) return 'collected';
    if (velocityMetrics?.absentSet?.has(dateStr)) return 'absent';
    return 'missing';
  };

  const getCellColor = (dateStr: string | null): string => {
    if (!dateStr) return "";
    const status = getCellStatus(dateStr);
    const base = CELL_STATUS_COLORS[status];
    const isFocused = focusedCell === dateStr;
    return isFocused ? `${base} heatmap-focused heatmap-cell` : `${base} heatmap-cell`;
  };

  const getAriaLabel = (dateStr: string | null): string => {
    if (!dateStr) return "Empty cell";
    const status = getCellStatus(dateStr);
    if (status === 'outside') return `${dateStr}: Before Tribunal Joined`;
    if (status === 'absent') return `${dateStr}: Confirmed Absent (No journal published)`;
    return `${dateStr}: ${status === 'collected' ? 'Collected' : 'Missing'}`;
  };

  const handleCellInteraction = (e: any, dateStr: string | null, type: string) => {
    if (e && e.stopPropagation) e.stopPropagation();
    if (!dateStr) return;
    if (type === 'leave') {
      setHoveredCell(null);
      return;
    }
    if (type === 'touch') {
      if (e && e.cancelable) e.preventDefault();
      const pos = { x: e.touches[0].clientX, y: e.touches[0].clientY };
      if (hoveredCell?.data?.date === dateStr) {
        setHoveredCell(null);
      } else {
        setHoveredCell({
          data: { date: dateStr, status: getCellStatus(dateStr), uploadedAt: null, sizeMb: null },
          position: pos
        });
      }
      return;
    }
    const pos = { x: e.clientX, y: e.clientY };
    if (type === 'click') {
      const status = getCellStatus(dateStr);
      if (status === 'collected' && baseUrl) {
        window.location.hash = dateStr;
        return;
      }
      if (hoveredCell?.data?.date === dateStr) {
        setHoveredCell(null);
        return;
      }
    }
    setHoveredCell({
      data: { date: dateStr, status: getCellStatus(dateStr), uploadedAt: null, sizeMb: null },
      position: pos
    });
  };

  const handleGridKeyDown = (e: any) => {
    if (!allDays.length) return;
    let currentIndex = focusedCell ? allDays.indexOf(focusedCell) : allDays.length - 1;
    if (currentIndex === -1) currentIndex = allDays.length - 1;
    let newIndex = currentIndex;
    switch (e.key) {
      case 'ArrowLeft': newIndex = Math.max(0, currentIndex - 1); e.preventDefault(); break;
      case 'ArrowRight': newIndex = Math.min(allDays.length - 1, currentIndex + 1); e.preventDefault(); break;
      case 'ArrowUp': newIndex = Math.max(0, currentIndex - 7); e.preventDefault(); break;
      case 'ArrowDown': newIndex = Math.min(allDays.length - 1, currentIndex + 7); e.preventDefault(); break;
      case 'Enter':
      case ' ':
        if (focusedCell) {
          e.preventDefault();
          const cellEl = document.getElementById(`cell-${focusedCell}`);
          const rect = cellEl ? cellEl.getBoundingClientRect() : { x: window.innerWidth / 2, y: window.innerHeight / 2 };
          handleCellInteraction({ clientX: rect.x + 6, clientY: rect.y + 6, stopPropagation: () => {} }, focusedCell, 'click');
        }
        break;
      case 'Escape': setHoveredCell(null); e.preventDefault(); break;
      default: return;
    }
    if (newIndex !== currentIndex && allDays[newIndex]) {
      setFocusedCell(allDays[newIndex]);
    }
  };

  const weekdayHeaders = ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'];

  return (
    <div className="flex flex-col gap-8">
      <div
        className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4"
        role="grid"
        aria-label={`Calendário de cobertura para ${tribunalName}`}
        tabIndex={0}
        onKeyDown={handleGridKeyDown}
        onFocus={() => { if (!focusedCell) setFocusedCell(allDays[allDays.length - 1]); }}
        onBlur={() => { setFocusedCell(null); setHoveredCell(null); }}
      >
        {months.map((m) => (
          <div key={`${m.year}-${m.month}`} className="card bg-base-100 border border-base-300 p-3">
            <h5 className="text-sm font-semibold capitalize mb-2">{m.label}</h5>
            <table className="w-full">
              <thead>
                <tr>
                  {weekdayHeaders.map((d) => (
                    <th key={d} className="text-xs opacity-50 font-normal text-center pb-1">{d}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {m.weeks.map((week, wi) => (
                  <tr key={`${m.year}-${m.month}-w${wi}`} role="row">
                    {week.map((day, di) => (
                      <td
                        key={day || `empty-${m.year}-${m.month}-${wi}-${di}`}
                        id={day ? `cell-${day}` : undefined}
                        role="gridcell"
                        className={`text-center text-xs p-0.5 ${day ? `rounded-sm ${getCellColor(day)} ${day && getCellStatus(day) === 'collected' && baseUrl ? 'cursor-pointer' : 'cursor-default'}` : ''}`}
                        aria-label={getAriaLabel(day)}
                        aria-selected={focusedCell === day}
                        onMouseEnter={(e: any) => handleCellInteraction(e, day, 'enter')}
                        onMouseMove={(e: any) => handleCellInteraction(e, day, 'move')}
                        onMouseLeave={(e: any) => handleCellInteraction(e, day, 'leave')}
                        onTouchStart={(e: any) => handleCellInteraction(e, day, 'touch')}
                        onClick={(e: any) => { handleCellInteraction(e, day, 'click'); setFocusedCell(day); }}
                      >
                        {day ? new Date(day + 'T00:00:00Z').getUTCDate() : ''}
                      </td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ))}
      </div>

      <div className="card bg-base-200">
        <div className="card-body p-4 flex-row justify-between items-center text-sm flex-wrap gap-4">
          <span className="opacity-70">
            <strong>{coveredDays}</strong> de <strong>{totalDays}</strong> dias com dados
          </span>
          <div className="flex items-center flex-wrap gap-6">
            <span className="opacity-50">Legenda:</span>
            <div className="flex items-center gap-2">
              <div className="heatmap-missing w-3.5 h-3.5 rounded-sm"></div>
              <span>Faltante</span>
            </div>
            <div className="flex items-center gap-2">
              <div className="heatmap-absent w-3.5 h-3.5 rounded-sm"></div>
              <span>Ausente</span>
            </div>
            <div className="flex items-center gap-2">
              <div className="heatmap-collected w-3.5 h-3.5 rounded-sm"></div>
              <span>Coletado</span>
            </div>
          </div>
        </div>
      </div>

      {velocityMetrics && velocityMetrics.hasEnoughHistory && (
        <div className="border-t border-base-300 pt-6 mt-10">
          <VelocityTimeline metrics={velocityMetrics} />
        </div>
      )}

      {hoveredCell && <CellTooltip cellData={hoveredCell.data} position={hoveredCell.position} />}
    </div>
  );
}
