// dashboard/src/components/PerfDashboard.svelte
<script lang="ts">
  import * as Plot from '@observablehq/plot';
  import LiveStatusWidget from './LiveStatusWidget.svelte';
  import PipelineRunHistory from './PipelineRunHistory.svelte';

  interface LatencyEntry {
    date: string;
    latency_ms: number;
  }

  interface SlowestTribunal {
    tribunal: string;
    velocity_14d: number;
  }

  interface QualityScore {
    grade: string;
    [key: string]: unknown;
  }

  interface Props {
    perfMetrics: {
      causaganha_collect_latency_ms?: LatencyEntry[];
      causaganha_upload_success_rate?: number;
      causaganha_backlog_pending_days?: number;
      causaganha_active_tribunals?: number;
      slowest_tribunals?: SlowestTribunal[];
    } | null;
    qualityScores: Record<string, QualityScore> | null;
  }

  let { perfMetrics, qualityScores } = $props<Props>();

  let chartEl: HTMLDivElement;
  let pieEl: HTMLDivElement;

  const latencies = $derived(perfMetrics?.causaganha_collect_latency_ms || []);
  const successRate = $derived(perfMetrics?.causaganha_upload_success_rate || 0);
  const backlogDays = $derived(perfMetrics?.causaganha_backlog_pending_days || 0);
  const activeTribunals = $derived(perfMetrics?.causaganha_active_tribunals || 0);
  const slowestTribunals = $derived(perfMetrics?.slowest_tribunals || []);

  const gradeData = $derived.by(() => {
    const gradeCounts: Record<string, number> = { A: 0, B: 0, C: 0, D: 0, F: 0 };
    if (qualityScores) {
      Object.values(qualityScores).forEach((score: QualityScore) => {
        if (gradeCounts[score.grade] !== undefined) {
          gradeCounts[score.grade]++;
        }
      });
    }
    return Object.entries(gradeCounts)
      .map(([grade, count]) => ({ grade, count }))
      .filter((d) => d.count > 0);
  });

  $effect(() => {
    if (chartEl && latencies.length > 0) {
      const data = latencies.map((d) => ({
        date: new Date(d.date),
        latency: d.latency_ms / 60000,
      }));

      const chart = Plot.plot({
        width: 800,
        height: 300,
        y: { label: 'Latency (minutes)', grid: true },
        x: { label: 'Date' },
        marks: [
          Plot.line(data, { x: 'date', y: 'latency', stroke: 'currentColor', strokeWidth: 2 }),
          Plot.dot(data, { x: 'date', y: 'latency', fill: 'currentColor', r: 4 }),
        ],
      });
      chartEl.innerHTML = '';
      chartEl.appendChild(chart);
    }

    if (pieEl && gradeData.length > 0) {
      const pie = Plot.plot({
        width: 400,
        height: 250,
        x: { label: 'Grade', domain: ['A', 'B', 'C', 'D', 'F'] },
        y: { label: 'Count', grid: true },
        color: {
          domain: ['A', 'B', 'C', 'D', 'F'],
          range: ['#10b981', '#3b82f6', '#eab308', '#f97316', '#ef4444'],
        },
        marks: [Plot.barY(gradeData, { x: 'grade', y: 'count', fill: 'grade' })],
      });
      pieEl.innerHTML = '';
      pieEl.appendChild(pie);
    }
  });
</script>

{#if !perfMetrics || !qualityScores}
  <div>Loading performance data...</div>
{:else}
  <div>
    <div>
      <LiveStatusWidget />
    </div>

    <div class="grid">
      <div class="card bg-base-100 shadow-sm border border-base-300">
        <div class="card-body">
          <small>Upload Success Rate</small>
          <div class={successRate >= 90 ? 'text-success' : 'text-error'}>
            {successRate.toFixed(1)}%
          </div>
        </div>
      </div>

      <div class="card bg-base-100 shadow-sm border border-base-300">
        <div class="card-body">
          <small>Pending Backlog Days</small>
          <div class="text-accent">
            {backlogDays}
          </div>
        </div>
      </div>

      <div class="card bg-base-100 shadow-sm border border-base-300">
        <div class="card-body">
          <small>Active Tribunals</small>
          <div>
            {activeTribunals}
          </div>
        </div>
      </div>
    </div>

    <div class="card bg-base-100 shadow-sm border border-base-300">
      <div class="card-body">
        <h3>Collection Latency Trend (7 days)</h3>
        <div bind:this={chartEl}></div>
        {#if latencies.length === 0}
          <div>No latency data available.</div>
        {/if}
      </div>
    </div>

    <div class="grid">
      <div class="card bg-base-100 shadow-sm border border-base-300">
        <div class="card-body">
          <h3>Grade Distribution</h3>
          <div bind:this={pieEl}></div>
        </div>
      </div>

      <div class="card bg-base-100 shadow-sm border border-base-300">
        <div class="card-body">
          <h3>Top 5 Slowest Tribunals</h3>
          <ul>
            {#each slowestTribunals as t, idx}
              <li>
                <span>{idx + 1}. {t.tribunal}</span>
                <span>{t.velocity_14d.toFixed(1)} velocity (14d)</span>
              </li>
            {/each}
            {#if slowestTribunals.length === 0}
              <li>All tribunals are up to date!</li>
            {/if}
          </ul>
        </div>
      </div>
    </div>

    <div>
      <PipelineRunHistory />
    </div>
  </div>
{/if}

// dashboard/src/components/PerfDashboard.jsx
import { useState, useEffect, useRef } from 'preact/compat';
import * as Plot from '@observablehq/plot';
import { LiveStatusWidget } from './LiveStatusWidget';

export function PerfDashboard({ perfMetrics, qualityScores }) {
  if (!perfMetrics || !qualityScores) {
    return <div className="p-8 text-center text-gray-500">Loading performance data...</div>;
  }

  const chartRef = useRef(null);
  const pieRef = useRef(null);
  const barRef = useRef(null);

  const latencies = perfMetrics.causaganha_collect_latency_ms || [];
  const successRate = perfMetrics.causaganha_upload_success_rate || 0;
  const backlogDays = perfMetrics.causaganha_backlog_pending_days || 0;
  const activeTribunals = perfMetrics.causaganha_active_tribunals || 0;
  const slowestTribunals = perfMetrics.slowest_tribunals || [];

  // Grade Distribution
  const gradeCounts = { A: 0, B: 0, C: 0, D: 0, F: 0 };
  Object.values(qualityScores).forEach(score => {
    if (gradeCounts[score.grade] !== undefined) {
      gradeCounts[score.grade]++;
    }
  });

  const gradeData = Object.entries(gradeCounts).map(([grade, count]) => ({ grade, count })).filter(d => d.count > 0);

  useEffect(() => {
    if (chartRef.current && latencies.length > 0) {
      const data = latencies.map(d => ({
        date: new Date(d.date),
        latency: d.latency_ms / 60000 // Convert to minutes
      }));

      const chart = Plot.plot({
        width: 800,
        height: 300,
        y: { label: "Latency (minutes)", grid: true },
        x: { label: "Date" },
        marks: [
          Plot.line(data, { x: "date", y: "latency", stroke: "currentColor", strokeWidth: 2 }),
          Plot.dot(data, { x: "date", y: "latency", fill: "currentColor", r: 4 })
        ]
      });
      chartRef.current.innerHTML = "";
      chartRef.current.appendChild(chart);
    }

    if (pieRef.current && gradeData.length > 0) {
      // Basic pie representation using Plot.rect or similar, or just D3. Observable plot 0.6 has some support but let's use a simple bar for distribution since Plot doesn't do pie easily out of the box in this version
      const pie = Plot.plot({
        width: 400,
        height: 250,
        x: { label: "Grade", domain: ["A", "B", "C", "D", "F"] },
        y: { label: "Count", grid: true },
        color: {
          domain: ["A", "B", "C", "D", "F"],
          range: ["#10b981", "#3b82f6", "#eab308", "#f97316", "#ef4444"] // cyber.success, info, warning...
        },
        marks: [
          Plot.barY(gradeData, { x: "grade", y: "count", fill: "grade" })
        ]
      });
      pieRef.current.innerHTML = "";
      pieRef.current.appendChild(pie);
    }
  }, [latencies, gradeData]);

  return (
    <div className="space-y-8">
      <div className="w-full">
        <LiveStatusWidget />
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="card text-center p-6">
          <div className="text-sm text-gray-500 mb-2">Upload Success Rate</div>
          <div className={`text-4xl font-bold ${successRate >= 90 ? 'text-success' : 'text-danger'}`}>
            {successRate.toFixed(1)}%
          </div>
        </div>

        <div className="card text-center p-6">
          <div className="text-sm text-gray-500 mb-2">Pending Backlog Days</div>
          <div className="text-4xl font-bold text-accent">
            {backlogDays}
          </div>
        </div>

        <div className="card text-center p-6">
          <div className="text-sm text-gray-500 mb-2">Active Tribunals</div>
          <div className="text-4xl font-bold text-black dark:text-white">
            {activeTribunals}
          </div>
        </div>
      </div>

      <div className="card p-6">
        <h3 className="text-lg font-semibold mb-4 text-black dark:text-white">Collection Latency Trend (7 days)</h3>
        <div ref={chartRef} className="w-full overflow-x-auto text-black dark:text-white" />
        {latencies.length === 0 && <div className="text-gray-500">No latency data available.</div>}
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="card p-6">
          <h3 className="text-lg font-semibold mb-4 text-black dark:text-white">Grade Distribution</h3>
          <div ref={pieRef} className="w-full text-black dark:text-white" />
        </div>

        <div className="card p-6">
          <h3 className="text-lg font-semibold mb-4 text-black dark:text-white">Top 5 Slowest Tribunals</h3>
          <ul className="space-y-4">
            {slowestTribunals.map((t, idx) => (
              <li key={t.tribunal} className="flex justify-between items-center border-b border-gray-100 dark:border-slate-800 pb-2">
                <span className="font-medium text-black dark:text-white">{idx + 1}. {t.tribunal}</span>
                <span className="text-sm text-gray-500">{t.velocity_14d.toFixed(1)} velocity (14d)</span>
              </li>
            ))}
            {slowestTribunals.length === 0 && <li className="text-gray-500">All tribunals are up to date!</li>}
          </ul>
        </div>
      </div>
    </div>
  );
}
