// dashboard/src/components/TribunalDetail.jsx
import { useState, useEffect, useCallback } from 'preact/compat';
import clsx from 'clsx';
import { useDataRefresh } from '../lib/useDataRefresh';
import { TRIBUNAIS } from '../lib/tribunais.js';
import { Heatmap, VelocityTimeline, calculateVelocityAndRegression } from './Heatmap';
import { DateDetail } from './DateDetail';

function parseHash() {
  if (typeof window === 'undefined') return { date: null, page: null, seq: null };
  const hash = window.location.hash.replace(/^#/, '');
  if (!hash) return { date: null, page: null, seq: null };
  const parts = hash.split('/');
  return {
    date: parts[0] || null,
    page: parts[1] ? parseInt(parts[1]) : null,
    seq: parts[2] ? parseInt(parts[2]) : null,
  };
}

export function TribunalDetail({ tribunalCode, initialCoverage, initialEtas, initialTargetRange, initialStartDates, initialQualityScores }) {
  const { data: allData } = useDataRefresh(null, null);
  const [selectedTribunal, setSelectedTribunal] = useState(tribunalCode.toUpperCase());
  const [hashState, setHashState] = useState(parseHash);

  // Listen for hash changes (back/forward navigation)
  useEffect(() => {
    const onHashChange = () => setHashState(parseHash());
    window.addEventListener('hashchange', onHashChange);
    return () => window.removeEventListener('hashchange', onHashChange);
  }, []);

  const coverage = allData?.tribunalCoverage ?? initialCoverage ?? {};
  const absentCoverage = allData?.tribunalAbsentCoverage ?? {};
  const etas = allData?.tribunalEtas ?? initialEtas ?? {};
  const startDates = allData?.tribunalStartDates ?? initialStartDates ?? {};
  const qualityScores = allData?.tribunalQualityScores ?? initialQualityScores ?? {};
  const iaSnapshot = allData?.iaSnapshot;

  // Date from hash, or most recent from snapshot
  let activeDate = hashState.date;
  if (!activeDate && iaSnapshot?.items) {
    for (const item of Object.values(iaSnapshot.items)) {
      if (item.tribunal === selectedTribunal) {
        if (!activeDate || item.latest_date > activeDate) {
          activeDate = item.latest_date;
        }
      }
    }
  }

  // Derive targetRange dynamically — no hardcoded dates
  const backfillTargetRange = allData?.targetRange ?? initialTargetRange;
  const today = new Date().toISOString().split('T')[0];
  const targetRange = {
    start: backfillTargetRange?.start || "2024-01-01",
    end: backfillTargetRange?.end || today,
  };

  const BASE = typeof import.meta !== 'undefined' ? (import.meta.env?.BASE_URL || '/causaganha/') : '/causaganha/';
  const baseUrl = BASE.endsWith('/') ? BASE : BASE + '/';

  const handleTribunalChange = (e) => {
    const newTribunal = e.target.value;
    setSelectedTribunal(newTribunal);
    window.location.href = `${baseUrl}publicacoes/${newTribunal.toLowerCase()}`;
  };

  // Build coverage from IA snapshot (real ZIPs on IA) — prefer over backfill data
  const snapshotDates = new Set();
  if (iaSnapshot?.items) {
    for (const item of Object.values(iaSnapshot.items)) {
      if (item.tribunal === selectedTribunal) {
        item.dates.forEach(d => snapshotDates.add(d));
      }
    }
  }
  const selectedCoverage = snapshotDates.size > 0 ? snapshotDates : new Set(coverage[selectedTribunal] || []);
  const selectedEtaData = etas[selectedTribunal] || { missing_days: null, velocity_14d: 0, eta_days: null };
  const tribunalStartDate = startDates[selectedTribunal] || selectedEtaData.genesis_date;

  // Calculate expected days from tribunal start to target end
  let expectedDays = 0;
  if (tribunalStartDate) {
    const start = new Date(tribunalStartDate + "T00:00:00Z");
    const end = new Date(targetRange.end + "T00:00:00Z");
    if (start <= end) {
      expectedDays = Math.floor((end - start) / (1000 * 60 * 60 * 24)) + 1;
    }
  }

  const actualMissingDays = selectedEtaData.missing_days !== null
    ? selectedEtaData.missing_days
    : Math.max(0, expectedDays - selectedCoverage.size);

  const isStopped = selectedEtaData.stopped || false;
  const cursorDate = selectedEtaData.cursor_date;
  const completionPct = selectedEtaData.completion_pct || 0;
  const genesisDate = selectedEtaData.genesis_date || tribunalStartDate;

  const velocityMetrics = calculateVelocityAndRegression(selectedCoverage, targetRange.end, tribunalStartDate);

  let dynamicEtaDays = selectedEtaData.eta_days;
  if (velocityMetrics && velocityMetrics.currentVelocity > 0 && actualMissingDays > 0) {
    dynamicEtaDays = Math.ceil(actualMissingDays / (velocityMetrics.currentVelocity / 7));
  }

  let etaText = "Pending";
  if (actualMissingDays === 0 && expectedDays > 0) {
    etaText = "Complete";
  } else if (dynamicEtaDays) {
    if (dynamicEtaDays < 30) {
      etaText = `~${dynamicEtaDays} days`;
    } else {
      const months = Math.round(dynamicEtaDays / 30);
      etaText = `~${months} month${months > 1 ? 's' : ''}`;
    }
  }

  const isComplete = actualMissingDays === 0 && expectedDays > 0;
  const statusColor = isComplete ? "text-success" : "text-warning";

  const absentList = absentCoverage[selectedTribunal] || [];
  const absentSet = new Set(absentList);

  const totalForBar = actualMissingDays + selectedCoverage.size + (selectedEtaData.absent_days_count || 0);

  return (
    <div className="flex flex-col gap-6">
      <div className="flex items-center justify-between mb-2">
        <a
          href={`${baseUrl}publicacoes`}
          className="flex items-center gap-2 text-sm font-medium text-gray-500 hover:text-black dark:text-gray-400 dark:hover:text-white transition-colors"
        >
          <svg className="w-4 h-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
          </svg>
          Voltar
        </a>
      </div>

      <div className="card p-4 flex flex-col lg:flex-row gap-6">
        {/* Sidebar */}
        <div className="w-full lg:w-64 flex flex-col gap-4 flex-shrink-0">
          <div>
            <label htmlFor="tribunal-select" className="block text-sm font-medium text-black dark:text-white mb-2">
              Tribunal
            </label>
            <select
              id="tribunal-select"
              value={selectedTribunal}
              onChange={handleTribunalChange}
              className="w-full bg-white dark:bg-slate-900 border border-gray-200 dark:border-slate-700 rounded-lg px-3 py-2 text-black dark:text-white focus:outline-none focus:border-accent"
            >
              {TRIBUNAIS.map(t => (
                <option key={t} value={t}>{t}</option>
              ))}
            </select>
          </div>

          <div className="flex flex-col gap-2 p-3 bg-gray-50 dark:bg-slate-800 rounded-lg border border-gray-100 dark:border-slate-800 relative">
            <div className="flex items-center justify-between">
              <h3 className="text-lg font-semibold text-black dark:text-white">{selectedTribunal}</h3>
              {qualityScores[selectedTribunal] && (
                <div
                  className={clsx(
                    "text-[10px] font-bold px-1.5 py-0.5 rounded cursor-help",
                    qualityScores[selectedTribunal].grade === 'A' ? "bg-success text-white" :
                    qualityScores[selectedTribunal].grade === 'B' ? "bg-info text-white" :
                    qualityScores[selectedTribunal].grade === 'C' ? "bg-warning text-white" :
                    qualityScores[selectedTribunal].grade === 'D' ? "bg-danger text-white" :
                    "bg-gray-500 text-white"
                  )}
                  title={`Completeness: ${qualityScores[selectedTribunal].completeness}%\nRecency: ${qualityScores[selectedTribunal].recency}%\nConsistency: ${qualityScores[selectedTribunal].consistency}%`}
                >
                  Grade {qualityScores[selectedTribunal].grade}
                </div>
              )}
            </div>

            <div className="text-sm flex justify-between mt-2">
              <span className="text-gray-600 dark:text-gray-300">Genesis</span>
              <span className="font-mono text-black dark:text-white">{genesisDate || "Unknown"}</span>
            </div>

            <div className="mt-2 mb-4">
              <div className="flex justify-between text-[11px] mb-1.5">
                <span className="text-gray-500 uppercase tracking-wider font-bold">Archiving Progress</span>
                <span className="font-mono font-bold text-accent">{completionPct}%</span>
              </div>
              <div className="h-3 w-full bg-gray-100 dark:bg-slate-800 rounded-full overflow-hidden flex shadow-inner">
                <div
                  className="h-full bg-gradient-to-r from-accent to-accent-light transition-all duration-700 ease-out"
                  style={{ width: totalForBar > 0 ? `${(selectedCoverage.size / totalForBar) * 100}%` : '0%' }}
                  title={`Sincronizado: ${selectedCoverage.size} ZIPs`}
                />
                <div
                  className="h-full bg-warning opacity-70 transition-all duration-700 ease-out"
                  style={{ width: totalForBar > 0 ? `${((selectedEtaData.absent_days_count || 0) / totalForBar) * 100}%` : '0%' }}
                  title={`Vazio Confirmado: ${selectedEtaData.absent_days_count || 0} dias`}
                />
              </div>
              <div className="flex justify-between mt-2 text-[9px] font-bold uppercase tracking-tighter">
                <div className="flex items-center gap-1.5 grayscale opacity-70">
                  <div className="w-2 h-2 rounded-full bg-accent"></div>
                  <span>{totalForBar > 0 ? ((selectedCoverage.size / totalForBar) * 100).toFixed(1) : '0.0'}% Sync</span>
                </div>
                <div className="flex items-center gap-1.5 text-right grayscale opacity-70">
                  <span>{totalForBar > 0 ? (((selectedEtaData.absent_days_count || 0) / totalForBar) * 100).toFixed(1) : '0.0'}% Absent</span>
                  <div className="w-2 h-2 rounded-full bg-warning"></div>
                </div>
              </div>
            </div>

            <div className="text-sm flex justify-between">
              <span className="text-gray-600 dark:text-gray-300">Status</span>
              <span className={`font-medium ${statusColor}`}>{etaText}</span>
            </div>

            <div className="text-sm flex justify-between">
              <span className="text-gray-600 dark:text-gray-300">Missing</span>
              <span className="font-mono text-black dark:text-white">{actualMissingDays} days</span>
            </div>

            {cursorDate && !isStopped && (
              <div className="text-sm flex justify-between">
                <span className="text-gray-600 dark:text-gray-300">Scanning cursor</span>
                <span className="font-mono text-xs font-semibold text-accent animate-pulse">{cursorDate}</span>
              </div>
            )}

            {isStopped && (
              <div className="mt-1">
                <span className="badge badge-danger text-[10px] w-full justify-center">
                  Stopped (60d Empty Streak)
                </span>
              </div>
            )}
          </div>
        </div>

        {/* Main: Heatmap area */}
        <div className="flex-1 overflow-x-auto custom-scrollbar pb-4">
          <Heatmap
            globalStartDateStr={targetRange.start}
            globalEndDateStr={targetRange.end}
            tribunalStartDateStr={tribunalStartDate}
            coverageSet={selectedCoverage}
            tribunalName={selectedTribunal}
            baseUrl={baseUrl}
            velocityMetrics={{
              ...velocityMetrics,
              absentSet: absentSet
            }}
          />
        </div>
      </div>

      {/* Publications for active date */}
      {activeDate && (
        <DateDetail
          tribunalCode={tribunalCode}
          dateStr={activeDate}
          initialPage={hashState.page}
          initialSeq={hashState.seq}
        />
      )}
    </div>
  );
}

// dashboard/src/components/TribunalDetail.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { createDataRefresh } from '../lib/dataRefreshStore';
  import { TRIBUNAIS, TRIBUNAL_GROUPS } from '../lib/tribunais';
  import { toDateString } from '../lib/dateUtils';
  import Heatmap from './Heatmap.svelte';
  import { calculateVelocityAndRegression } from '../lib/velocityCalc';
  import DateDetail from './DateDetail.svelte';
  import DataAccessPanel from './DataAccessPanel.svelte';

  interface HashState {
    date: string | null;
    page: number | null;
    seq: number | null;
  }

  function parseHash(): HashState {
    if (typeof window === 'undefined') return { date: null, page: null, seq: null };
    const hash = window.location.hash.replace(/^#/, '');
    if (!hash) return { date: null, page: null, seq: null };
    const parts = hash.split('/');
    return {
      date: parts[0] || null,
      page: parts[1] ? parseInt(parts[1]) : null,
      seq: parts[2] ? parseInt(parts[2]) : null,
    };
  }

  interface TribunalDetailProps {
    tribunalCode: string;
    initialCoverage: Record<string, string[]> | null;
    initialEtas: Record<string, any> | null;
    initialTargetRange: { start: string; end: string } | null;
    initialStartDates: Record<string, string> | null;
    initialQualityScores: Record<string, any> | null;
  }

  let {
    tribunalCode,
    initialCoverage,
    initialEtas,
    initialTargetRange,
    initialStartDates,
    initialQualityScores,
  }: TribunalDetailProps = $props();

  const store = createDataRefresh(null, null);
  onMount(() => store.start());
  onDestroy(() => store.stop());

  let selectedTribunal = $state(tribunalCode.toUpperCase());
  let hashState = $state<HashState>({ date: null, page: null, seq: null });
  let hashReady = $state(false);

  onMount(() => {
    hashState = parseHash();
    hashReady = true;
    const onHashChange = () => { hashState = parseHash(); };
    window.addEventListener('hashchange', onHashChange);
    return () => window.removeEventListener('hashchange', onHashChange);
  });

  let allData = $derived($store.data);

  let coverage = $derived(allData?.tribunalCoverage ?? initialCoverage ?? {});
  let absentCoverage = $derived(allData?.tribunalAbsentCoverage ?? {});
  let etas = $derived(allData?.tribunalEtas ?? initialEtas ?? {});
  let startDates = $derived(allData?.tribunalStartDates ?? initialStartDates ?? {});
  let qualityScores = $derived(allData?.tribunalQualityScores ?? initialQualityScores ?? {});
  let iaSnapshot = $derived(allData?.iaSnapshot);

  let activeDate = $derived.by(() => {
    let date = hashState.date;
    if (!date && iaSnapshot?.items) {
      for (const item of Object.values(iaSnapshot.items)) {
        if (item.tribunal === selectedTribunal) {
          if (!date || item.latest_date > date) {
            date = item.latest_date;
          }
        }
      }
    }
    return date;
  });

  let backfillTargetRange = $derived(allData?.targetRange ?? initialTargetRange);
  let today = $derived(toDateString(new Date()));
  let targetRange = $derived({
    start: backfillTargetRange?.start || "2024-01-01",
    end: backfillTargetRange?.end || today,
  });

  const BASE = typeof import.meta !== 'undefined' ? (import.meta.env?.BASE_URL || '/causaganha/') : '/causaganha/';
  const baseUrl = BASE.endsWith('/') ? BASE : BASE + '/';

  function handleTribunalChange(e: Event) {
    const newTribunal = (e.target as HTMLSelectElement).value;
    if (!TRIBUNAIS.includes(newTribunal)) return;
    selectedTribunal = newTribunal;
    window.location.href = `${baseUrl}publicacoes/${encodeURIComponent(newTribunal.toLowerCase())}`;
  }

  let snapshotDates = $derived.by(() => {
    const dates = new Set<string>();
    if (iaSnapshot?.items) {
      for (const item of Object.values(iaSnapshot.items)) {
        if (item.tribunal === selectedTribunal) {
          item.dates.forEach((d: string) => dates.add(d));
        }
      }
    }
    return dates;
  });

  let selectedCoverage = $derived(snapshotDates.size > 0 ? snapshotDates : new Set(coverage[selectedTribunal] || []));
  let selectedEtaData = $derived(etas[selectedTribunal] || { missing_days: null, velocity_14d: 0, eta_days: null });
  let tribunalStartDate = $derived(startDates[selectedTribunal] || selectedEtaData.genesis_date);

  let expectedDays = $derived.by(() => {
    if (!tribunalStartDate) return 0;
    const start = new Date(tribunalStartDate + "T00:00:00Z");
    const end = new Date(targetRange.end + "T00:00:00Z");
    if (start <= end) {
      return Math.floor((end.getTime() - start.getTime()) / (1000 * 60 * 60 * 24)) + 1;
    }
    return 0;
  });

  let actualMissingDays = $derived(
    selectedEtaData.missing_days !== null
      ? selectedEtaData.missing_days
      : Math.max(0, expectedDays - selectedCoverage.size)
  );

  let isStopped = $derived(selectedEtaData.stopped || false);
  let cursorDate = $derived(selectedEtaData.cursor_date);
  let completionPct = $derived(selectedEtaData.completion_pct || 0);
  let genesisDate = $derived(selectedEtaData.genesis_date || tribunalStartDate);

  let velocityMetrics = $derived(calculateVelocityAndRegression(selectedCoverage, targetRange.end, tribunalStartDate));

  let dynamicEtaDays = $derived.by(() => {
    let eta = selectedEtaData.eta_days;
    if (velocityMetrics && velocityMetrics.currentVelocity > 0 && actualMissingDays > 0) {
      eta = Math.ceil(actualMissingDays / (velocityMetrics.currentVelocity / 7));
    }
    return eta;
  });

  let etaText = $derived.by(() => {
    if (actualMissingDays === 0 && expectedDays > 0) return "Concluido";
    if (dynamicEtaDays) {
      if (dynamicEtaDays < 30) return `~${dynamicEtaDays} dias`;
      const months = Math.round(dynamicEtaDays / 30);
      return `~${months} ${months > 1 ? 'meses' : 'mes'}`;
    }
    return "Pendente";
  });

  let isComplete = $derived(actualMissingDays === 0 && expectedDays > 0);
  let statusColor = $derived(isComplete ? "text-success" : "text-warning");

  let absentList = $derived(absentCoverage[selectedTribunal] || []);
  let absentSet = $derived(new Set(absentList));

  let totalForBar = $derived(actualMissingDays + selectedCoverage.size + (selectedEtaData.absent_days_count || 0));
  let absentCount = $derived(selectedEtaData.absent_days_count || 0);
  let syncedPct = $derived(totalForBar > 0 ? (selectedCoverage.size / totalForBar) * 100 : 0);
  let completionStatusText = $derived(isComplete ? "Concluido" : "Em andamento");

  let hasFeaturedPub = $derived(hashState.seq != null);

  let iaYear = $derived(activeDate ? parseInt(activeDate.substring(0, 4)) : new Date().getFullYear());

  let qualityScore = $derived(qualityScores[selectedTribunal]);
  let qualityBadgeClass = $derived.by(() => {
    if (!qualityScore) return '';
    if (qualityScore.grade === 'A') return 'badge-success';
    if (qualityScore.grade === 'B') return 'badge-accent';
    if (qualityScore.grade === 'C') return 'badge-warning';
    return 'badge-error';
  });

  function exportCsv() {
    const rows = ["data,status"];
    snapshotDates.forEach(d => rows.push(`${d},coletado`));
    absentSet.forEach(d => rows.push(`${d},ausente`));
    const blob = new Blob([rows.join('\n')], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `cobertura-${selectedTribunal.toLowerCase()}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  }

  function shareLink() {
    navigator.clipboard.writeText(window.location.href);
    alert("Link copiado para a area de transferencia.");
  }
</script>

{#if !hashReady && typeof window !== 'undefined'}
  <div class="flex justify-center p-8"><span class="loading loading-spinner loading-lg"></span></div>
{:else}
  <div>
    {#if hasFeaturedPub && activeDate}
      <DateDetail
        tribunalCode={tribunalCode}
        dateStr={activeDate}
        initialPage={hashState.page}
        initialSeq={hashState.seq}
      />
    {/if}

    <div class="flex justify-between items-center mb-4">
      <div class="breadcrumbs mb-0">
        <ul>
          <li><a href={`${baseUrl}`}>CausaGanha</a></li>
          <li><a href={`${baseUrl}publicacoes`}>Publicacoes</a></li>
          <li>
            <select
              id="tribunal-select"
              value={selectedTribunal}
              onchange={handleTribunalChange}
              class="select select-ghost select-sm"
            >
              {#each TRIBUNAL_GROUPS as group}
                <optgroup label={group.name}>
                  {#each group.tribunals as t}
                    <option value={t}>{t}</option>
                  {/each}
                </optgroup>
              {/each}
            </select>
          </li>
        </ul>
      </div>
      <div class="flex gap-2">
        <button
          class="btn btn-sm btn-ghost"
          onclick={exportCsv}
          title="Exportar CSV de Cobertura"
          aria-label="Exportar CSV"
        >
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="7 10 12 15 17 10"></polyline><line x1="12" y1="15" x2="12" y2="3"></line></svg>
          Exportar CSV
        </button>
        <button
          class="btn btn-sm btn-ghost"
          onclick={shareLink}
          title="Copiar Link"
          aria-label="Compartilhar Link"
        >
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"></path><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"></path></svg>
          Compartilhar Link
        </button>
      </div>
    </div>

    <div class="flex justify-between items-end mb-6">
      <div>
        <h1 class="text-3xl font-bold">{selectedTribunal}</h1>
        {#if qualityScore}
          <span
            class={`badge mt-2 ${qualityBadgeClass}`}
            title={`Completude: ${qualityScore.completeness}%\nRecencia: ${qualityScore.recency}%\nConsistencia: ${qualityScore.consistency}%`}
          >
            Qualidade: {qualityScore.grade}
          </span>
        {/if}
      </div>
    </div>

    <div class="stats stats-vertical md:stats-horizontal shadow-sm border border-base-300 w-full mb-8">
      <div class="stat">
        <div class="stat-title">Progresso da Coleta</div>
        <div class="stat-value text-primary">{completionPct}%</div>
        <div class="stat-desc mt-1">
          <progress class="progress progress-primary w-full" value={Math.round(syncedPct)} max="100"></progress>
          <div class="flex justify-between mt-1">
            <span>{selectedCoverage.size} itens sincronizados</span>
            <span>{absentCount} dias ausentes</span>
          </div>
        </div>
      </div>

      <div class="stat">
        <div class="stat-title">Status</div>
        <div class={`stat-value ${statusColor}`}>{completionStatusText}</div>
        <div class="stat-desc">{etaText}</div>
      </div>

      <div class="stat">
        <div class="stat-title">Dias Faltantes</div>
        <div class="stat-value">{actualMissingDays}</div>
        <div class="stat-desc">A partir de {genesisDate || "Desconhecida"}</div>
      </div>
    </div>

    <div role="tablist" class="tabs tabs-lifted mb-8">
      <input type="radio" name="tribunal_tabs" role="tab" class="tab font-semibold" aria-label="Calendario" checked />
      <div role="tabpanel" class="tab-content bg-base-100 border-base-300 rounded-box p-4 md:p-6 shadow-sm">
        <Heatmap
          globalStartDateStr={targetRange.start}
          globalEndDateStr={targetRange.end}
          tribunalStartDateStr={tribunalStartDate}
          coverageSet={selectedCoverage}
          tribunalName={selectedTribunal}
          baseUrl={baseUrl}
          velocityMetrics={{
            ...velocityMetrics,
            absentSet: absentSet
          }}
        />
      </div>

      <input type="radio" name="tribunal_tabs" role="tab" class="tab font-semibold" aria-label="Estatisticas & Arquivo" />
      <div role="tabpanel" class="tab-content bg-base-100 border-base-300 rounded-box p-4 md:p-6 shadow-sm">
        <div class="grid md:grid-cols-2 gap-8">
          <div>
            <h3 class="text-xl mb-4">Informacoes do Pipeline</h3>
            <div class="space-y-4">
              <div>
                <small class="opacity-50 block uppercase tracking-widest text-xs">Data inicial do tribunal</small>
                <strong class="text-sm">{genesisDate || "Desconhecida"}</strong>
              </div>

              {#if cursorDate && !isStopped}
                <div>
                  <small class="opacity-50 block uppercase tracking-widest text-xs">Cursor de varredura atual</small>
                  <strong class="text-primary text-sm">{cursorDate}</strong>
                </div>
              {/if}

              {#if isStopped}
                <div class="alert alert-error">
                  <span>Pipeline interrompido (60 dias sem publicacoes identificadas).</span>
                </div>
              {/if}
            </div>
          </div>

          <div>
            <h3 class="text-xl mb-4">Internet Archive</h3>
            <div class="space-y-6">
              <a
                href={`https://archive.org/details/djen-${selectedTribunal.toLowerCase()}-${iaYear}`}
                target="_blank"
                rel="noopener noreferrer"
                class="btn btn-outline btn-sm w-full sm:w-auto"
              >
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" style="width: 1.25rem; height: 1.25rem;">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
                </svg>
                Ver colecao de {iaYear} no IA
              </a>
              <div class="bg-base-200 p-4 rounded-lg">
                <DataAccessPanel
                  tribunalCode={selectedTribunal}
                  year={iaYear}
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    {#if activeDate && !hasFeaturedPub}
      <DateDetail
        tribunalCode={tribunalCode}
        dateStr={activeDate}
        initialPage={hashState.page}
      />
    {/if}
  </div>
{/if}
