// dashboard/src/components/TribunalView.tsx
import { useMemo, useState } from 'preact/hooks';
import { useDataRefresh } from '../lib/useDataRefresh';
import { TRIBUNAL_GROUPS } from '../lib/tribunais';

interface TribunalViewProps {
  initialPipeline: any;
  initialProgressByYear: Record<string, any> | null;
  initialVolume: any;
  initialIaSnapshot: any;
}

export function TribunalView({ initialPipeline, initialProgressByYear, initialVolume, initialIaSnapshot }: TribunalViewProps) {
  const { data: allData } = useDataRefresh(null, null);

  const pipeline = allData?.cacheData?.today?.pipeline ?? initialPipeline;
  const progressByYear = allData?.progressByYear ?? initialProgressByYear;
  const volume = allData?.volume ?? initialVolume;
  const iaSnapshot = allData?.iaSnapshot ?? initialIaSnapshot;

  return (
    <OverviewGrid
      pipeline={pipeline} progressByYear={progressByYear}
      volume={volume}
      iaSnapshot={iaSnapshot}
    />
  );
}

interface OverviewGridProps {
  pipeline: any;
  progressByYear: Record<string, any> | null;
  volume: any;
  iaSnapshot: any;
}

function OverviewGrid({ pipeline, progressByYear, volume, iaSnapshot }: OverviewGridProps) {
  const [query, setQuery] = useState('');

  const snap = iaSnapshot?.summary;
  const totalZips = snap?.total_zips || pipeline?.total_zips || 0;
  const totalGB = snap?.total_size_gb || volume?.total_gb || 0;
  const tribunalsWithData = snap?.tribunals_with_data || 0;
  const latestDate = snap?.latest_collection_date;
  const snapshotAge = iaSnapshot?.generated_at;

  const snapshotItems = iaSnapshot?.items || {};
  const snapshotByYear = iaSnapshot?.by_year || {};

  const BASE = typeof import.meta !== 'undefined' ? (import.meta.env?.BASE_URL || '/causaganha/') : '/causaganha/';
  const baseUrl = BASE.endsWith('/') ? BASE : BASE + '/';
  const normalizedQuery = query.trim().toLowerCase();
  const filteredGroups = useMemo(() => {
    return TRIBUNAL_GROUPS
      .map(group => ({
        ...group,
        tribunals: group.tribunals.filter(tribunal => {
          if (!normalizedQuery) return true;
          return tribunal.toLowerCase().includes(normalizedQuery);
        }),
      }))
      .filter(group => group.tribunals.length > 0);
  }, [normalizedQuery]);

  return (
    <div>
      {/* Archive Progress */}
      <div className="card bg-base-100 shadow-sm border border-base-300 mb-16"><div className="card-body">
        <header className="pb-4 border-b border-base-300 mb-6">
          <div className="flex justify-between items-baseline flex-wrap gap-2 items-center">
            <h2 className="mb-0 text-2xl">Progresso do Arquivo</h2>
            {latestDate && (
              <span className="text-xs opacity-50">
                Última coleta: {latestDate}
                {snapshotAge && <span> · {new Date(snapshotAge).toLocaleString('pt-BR', { timeZone: 'UTC', hour: '2-digit', minute: '2-digit', day: '2-digit', month: '2-digit' })} UTC</span>}
              </span>
            )}
          </div>
        </header>

        {/* Quick Stats */}
        <div className="stats stats-vertical lg:stats-horizontal shadow-sm w-full mb-6">
          <div className="stat text-center">
            <div className="stat-value text-info">{totalZips.toLocaleString()}</div>
            <p className="stat-title mt-2">ZIPs no IA</p>
          </div>
          <div className="stat text-center">
            <div className="stat-value text-warning">{totalGB.toFixed(1)}<small className="font-medium" style={{ fontSize: '0.4em', marginLeft: '0.15em' }}>GB</small></div>
            <p className="stat-title mt-2">Volume</p>
          </div>
          <div className="stat text-center">
            <div className="stat-value text-success">{tribunalsWithData}<small className="font-normal opacity-50 text-base-content" style={{ fontSize: '0.4em', marginLeft: '0.15em' }}>/ {snap?.tribunals_total || 96}</small></div>
            <p className="stat-title mt-2">Tribunais</p>
          </div>
          <div className="stat text-center">
            <div className="stat-value text-primary">{snap?.total_items || 0}</div>
            <p className="stat-title mt-2">Itens no IA</p>
          </div>
        </div>
      </div></div>

      {/* Progress by Year */}
      {Object.keys(snapshotByYear).length > 0 ? (
        <div className="card bg-base-100 shadow-sm border border-base-300 mb-16"><div className="card-body">
          <header className="pb-4 border-b border-base-300 mb-6 flex justify-between items-baseline">
            <strong>ZIPs por Ano</strong>
            <small className="opacity-50 text-xs">Internet Archive</small>
          </header>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(150px, 1fr))', gap: '1rem' }}>
            {Object.entries(snapshotByYear)
              .sort(([a], [b]) => b.localeCompare(a))
              .map(([year, d]) => (
                <div className="card bg-base-100 shadow-sm border border-base-300 mb-0" key={year}><div className="card-body p-4">
                  <div className="flex justify-between items-baseline mb-2">
                    <strong className="text-sm">{year}</strong>
                    <span className="font-mono text-sm font-bold">{(d as any).zip_count.toLocaleString()}</span>
                  </div>
                  <small className="opacity-50 text-xs">
                    {(d as any).tribunals_with_data} / {(d as any).tribunals_total} tribunais
                  </small>
                </div></div>
              ))}
          </div>
        </div></div>
      ) : progressByYear && Object.keys(progressByYear).length > 0 ? (
        <div className="card bg-base-100 shadow-sm border border-base-300 mb-16"><div className="card-body">
          <header className="pb-4 border-b border-base-300 mb-6">
            <strong>Progresso por Ano</strong>
          </header>
          <div>
            {Object.entries(progressByYear)
              .sort(([a], [b]) => b.localeCompare(a))
              .map(([year, d]) => {
                const pct = (d as any).pct || 0;
                return (
                  <div key={year} className="mb-6">
                    <div className="flex justify-between items-baseline mb-2">
                      <strong className="text-sm">{year}</strong>
                      <span className="font-mono text-sm font-semibold">{pct.toFixed(1)}%</span>
                    </div>
                    <progress className="progress progress-primary" value={Math.round(Math.min(100, pct))} max="100" aria-label={`Progresso de coleta para o ano ${year}`}></progress>
                    <div className="opacity-50 text-xs flex gap-4 mt-2">
                      <span>{(d as any).zips || 0} ZIPs</span>
                      <span>{(d as any).days_consolidated || 0} consolidados</span>
                      <span>{(d as any).unique_days || 0} / {(d as any).weekdays || 0} dias</span>
                    </div>
                  </div>
                );
              })}
          </div>
        </div></div>
      ) : null}

      {/* Tribunal Filter */}
      <div className="mb-6 mt-10">
        <label htmlFor="tribunal-filter" className="text-sm font-medium opacity-70 mb-2 block">
          Filtrar tribunais
        </label>
        <label className="input input-bordered flex items-center gap-2 max-w-lg">
          <svg width="16" height="16" fill="currentColor" viewBox="0 0 16 16" className="opacity-50"><path fillRule="evenodd" d="M9.965 11.026a5 5 0 1 1 1.06-1.06l2.755 2.754a.75.75 0 1 1-1.06 1.06l-2.755-2.754ZM10.5 7a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0Z" clipRule="evenodd" /></svg>
          <input
            id="tribunal-filter" type="search"
            className="grow"
            value={query}
            onInput={(event) => setQuery((event.target as HTMLInputElement).value)}
            onKeyDown={(event) => {
              if (event.key === 'Escape') setQuery('');
            }}
            placeholder="Busque por sigla ou nome (ex.: tjsp, trf1, stj)"
            aria-label="Filtrar tribunais por sigla ou nome"
          />
          {query && <span className="badge badge-info badge-sm cursor-pointer" onClick={() => setQuery('')}>Limpar</span>}
        </label>
      </div>

      {/* Tribunal Groups */}
      {filteredGroups.length === 0 ? (
        <div className="empty-state">
          <svg fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" /></svg>
          <p className="mb-0">Nenhum tribunal encontrado para "{query.trim()}". Tente buscar por outra sigla ou nome.</p>
        </div>
      ) : filteredGroups.map(group => {
        return (
          <section key={group.name} className="mb-16">
            <div className="mb-6 pb-4 border-b border-base-300">
              <h3 className="text-xl mb-2" style={{ marginBottom: '0.25rem' }}>{group.name}</h3>
              <small className="opacity-50 text-xs">{group.tribunals.length} tribunais</small>
            </div>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(150px, 1fr))', gap: '1rem' }}>
              {group.tribunals.map(t => {
                let totalZips = 0;
                let latestDate = null;
                if (snapshotItems) {
                  for (const item of Object.values(snapshotItems)) {
                    if ((item as any).tribunal === t) {
                      totalZips += (item as any).zip_count;
                      if (!latestDate || (item as any).latest_date > latestDate) latestDate = (item as any).latest_date;
                    }
                  }
                }
                const hasData = totalZips > 0;

                return (
                  <a
                    key={t} href={`${baseUrl}publicacoes/${t.toLowerCase()}`}
                    style={{ textDecoration: 'none', color: 'inherit' }}>
                    <div className="card bg-base-100 shadow-sm border border-base-300 hover:shadow-md transition-shadow h-100"><div className="card-body p-4">
                      <div className="flex justify-between items-baseline items-center mb-2">
                        <strong className="text-sm">{t}</strong>
                        <span className={hasData ? "badge badge-success badge-sm" : "badge badge-error badge-sm"}>{hasData ? "Online" : "Offline"}</span>
                      </div>
                      <div className="text-xs opacity-70 mb-2">
                        {hasData ? `${totalZips.toLocaleString()} publicações` : 'Sem dados processados'}
                        {latestDate && <span className="block mt-1 opacity-70">Última: {latestDate}</span>}
                      </div>
                      <progress className={`progress w-full ${hasData ? 'progress-success' : 'progress-error'}`} value={hasData ? 100 : 0} max="100"></progress>
                    </div></div>
                  </a>
                );
              })}
            </div>
          </section>
        );
      })}
    </div>
  );
}

// web/src/components/TribunalView.svelte
<script lang="ts">
  import { TRIBUNAL_GROUPS } from '../lib/tribunais';
  import { useDashboardWithPolling } from '../lib/useDashboard.svelte';
  import QueryProvider from './QueryProvider.svelte';

  let {
    initialPipeline,
    initialProgressByYear,
    initialVolume,
    initialIaSnapshot,
  } = $props<{
    initialPipeline: any;
    initialProgressByYear: Record<string, any> | null;
    initialVolume: any;
    initialIaSnapshot: any;
  }>();

  const dashboard = useDashboardWithPolling();

  const pipeline = $derived(dashboard.data?.cacheData?.today?.pipeline ?? initialPipeline);
  const progressByYear = $derived(dashboard.data?.progressByYear ?? initialProgressByYear);
  const volume = $derived(dashboard.data?.volume ?? initialVolume);
  const iaSnapshot = $derived(dashboard.data?.iaSnapshot ?? initialIaSnapshot);

  let query = $state('');

  const snap = $derived(iaSnapshot?.summary);
  const totalZips = $derived(snap?.total_zips || pipeline?.total_zips || 0);
  const totalGB = $derived(snap?.total_size_gb || volume?.total_gb || 0);
  const tribunalsWithData = $derived(snap?.tribunals_with_data || 0);
  const latestDate = $derived(snap?.latest_collection_date);
  const snapshotAge = $derived(iaSnapshot?.generated_at);

  const snapshotItems = $derived(iaSnapshot?.items || {});
  const snapshotByYear = $derived(iaSnapshot?.by_year || {});

  const BASE = import.meta.env.BASE_URL;
  const baseUrl = BASE.endsWith('/') ? BASE : BASE + '/';

  const normalizedQuery = $derived(query.trim().toLowerCase());

  const filteredGroups = $derived(
    TRIBUNAL_GROUPS
      .map(group => ({
        ...group,
        tribunals: group.tribunals.filter(tribunal => {
          if (!normalizedQuery) return true;
          return tribunal.toLowerCase().includes(normalizedQuery);
        }),
      }))
      .filter(group => group.tribunals.length > 0)
  );

  function formatDate(iso: string): string {
    const [y, m, d] = iso.split('-');
    return `${d}/${m}/${y}`;
  }

  function getTribunalStats(t: string) {
    let totalZips = 0;
    let latestDate: string | null = null;
    if (snapshotItems) {
      for (const item of Object.values(snapshotItems)) {
        if ((item as any).tribunal === t) {
          totalZips += (item as any).zip_count;
          if (!latestDate || (item as any).latest_date > latestDate) latestDate = (item as any).latest_date;
        }
      }
    }
    return { totalZips, latestDate, hasData: totalZips > 0 };
  }
</script>

<QueryProvider>
<div>
  <!-- Archive Progress -->
  <div class="card card-lg"><div class="card-body">
    <header class="section-header">
      <div class="header-row">
        <h2 class="section-title">Progresso do Arquivo</h2>
        {#if latestDate}
          <span class="meta-text">
            Última coleta: {latestDate}
            {#if snapshotAge}
              <span> · {new Date(snapshotAge).toLocaleString('pt-BR', { timeZone: 'UTC', hour: '2-digit', minute: '2-digit', day: '2-digit', month: '2-digit' })} UTC</span>
            {/if}
          </span>
        {/if}
      </div>
    </header>

    <!-- Quick Stats -->
    <div class="stats">
      <div class="stat">
        <div class="stat-value value-info">{totalZips.toLocaleString()}</div>
        <p class="stat-title">ZIPs no IA</p>
      </div>
      <div class="stat">
        <div class="stat-value value-warning">{totalGB.toFixed(1)}<small class="unit-suffix">GB</small></div>
        <p class="stat-title">Volume</p>
      </div>
      <div class="stat">
        <div class="stat-value value-success">{tribunalsWithData}<small class="fraction-suffix">/ {snap?.tribunals_total || 96}</small></div>
        <p class="stat-title">Tribunais</p>
      </div>
      <div class="stat">
        <div class="stat-value value-primary">{snap?.total_items || 0}</div>
        <p class="stat-title">Itens no IA</p>
      </div>
    </div>
  </div></div>

  <!-- Progress by Year -->
  {#if Object.keys(snapshotByYear).length > 0}
    <div class="card card-lg"><div class="card-body">
      <header class="section-header header-row">
        <strong>ZIPs por Ano</strong>
        <small class="meta-text">Internet Archive</small>
      </header>
      <div class="auto-grid">
        {#each Object.entries(snapshotByYear).sort(([a], [b]) => b.localeCompare(a)) as [year, d]}
          <div class="card card-compact"><div class="card-body-sm">
            <div class="year-row">
              <strong class="small-text">{year}</strong>
              <span class="mono-value">{(d as any).zip_count.toLocaleString()}</span>
            </div>
            <small class="meta-text">
              {(d as any).tribunals_with_data} / {(d as any).tribunals_total} tribunais
            </small>
          </div></div>
        {/each}
      </div>
    </div></div>
  {:else if progressByYear && Object.keys(progressByYear).length > 0}
    <div class="card card-lg"><div class="card-body">
      <header class="section-header">
        <strong>Progresso por Ano</strong>
      </header>
      <div>
        {#each Object.entries(progressByYear).sort(([a], [b]) => b.localeCompare(a)) as [year, d]}
          {@const pct = (d as any).pct || 0}
          <div class="year-progress-block">
            <div class="year-row">
              <strong class="small-text">{year}</strong>
              <span class="mono-value-semibold">{pct.toFixed(1)}%</span>
            </div>
            <progress class="progress-bar progress-primary" value={Math.round(Math.min(100, pct))} max="100" aria-label={`Progresso de coleta para o ano ${year}`}></progress>
            <div class="progress-details">
              <span>{(d as any).zips || 0} ZIPs</span>
              <span>{(d as any).days_consolidated || 0} consolidados</span>
              <span>{(d as any).unique_days || 0} / {(d as any).weekdays || 0} dias</span>
            </div>
          </div>
        {/each}
      </div>
    </div></div>
  {/if}

  <!-- Tribunal Filter -->
  <div class="filter-section">
    <label for="tribunal-filter" class="filter-label">
      Filtrar tribunais
    </label>
    <label class="search-input-wrapper">
      <svg width="16" height="16" fill="currentColor" viewBox="0 0 16 16" class="search-icon"><path fill-rule="evenodd" d="M9.965 11.026a5 5 0 1 1 1.06-1.06l2.755 2.754a.75.75 0 1 1-1.06 1.06l-2.755-2.754ZM10.5 7a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0Z" clip-rule="evenodd" /></svg>
      <input
        id="tribunal-filter" type="search"
        class="search-input"
        value={query}
        oninput={(event) => query = (event.target as HTMLInputElement).value}
        onkeydown={(event) => {
          if (event.key === 'Escape') query = '';
        }}
        placeholder="Busque por sigla ou nome (ex.: tjsp, trf1, stj)"
        aria-label="Filtrar tribunais por sigla ou nome"
      />
      {#if query}
        <span class="badge badge-info badge-sm" onclick={() => query = ''}>Limpar</span>
      {/if}
    </label>
  </div>

  <!-- Tribunal Groups -->
  {#if filteredGroups.length === 0}
    <div class="empty-state">
      <svg fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" /></svg>
      <p class="no-margin">Nenhum tribunal encontrado para "{query.trim()}". Tente buscar por outra sigla ou nome.</p>
    </div>
  {:else}
    {#each filteredGroups as group}
      <section class="group-section">
        <div class="group-header">
          <h3 class="group-title" style="margin-bottom: 0.25rem">{group.name}</h3>
          <small class="meta-text">{group.tribunals.length} tribunais</small>
        </div>
        <div class="auto-grid">
          {#each group.tribunals as t}
            {@const stats = getTribunalStats(t)}
            <a
              href={`${baseUrl}publicacoes/${t.toLowerCase()}`}
              class="tribunal-link"
            >
              <div class="card tribunal-card" class:offline={!stats.hasData}>
                <div class="card-body-sm">
                  <div class="tribunal-card-header">
                    <strong class="small-text">{t}</strong>
                    <span class={stats.hasData ? "badge badge-success badge-sm" : "badge badge-error badge-sm"}>
                      {stats.hasData ? "Online" : "Offline"}
                    </span>
                  </div>
                  <div class="tribunal-card-meta">
                    {#if stats.hasData}
                      {stats.totalZips.toLocaleString()} publicações
                    {:else}
                      Sem dados processados
                    {/if}
                    {#if stats.latestDate}
                      <span class="latest-date">Última: {formatDate(stats.latestDate)}</span>
                    {/if}
                  </div>
                </div>
              </div>
            </a>
          {/each}
        </div>
      </section>
    {/each}
  {/if}
</div>
</QueryProvider>

<style>

  /* Cards */

  /* Section headers */

  .header-row {
    display: flex;
    justify-content: space-between;
    align-items: center;
    flex-wrap: wrap;
    gap: 0.5rem;
  }

  /* Stats */
  .stats {
    display: flex;
    flex-direction: column;
    border: 1px solid var(--color-base-300);
    border-radius: var(--radius-box);
    box-shadow: var(--shadow-sm);
    overflow: hidden;
    width: 100%;
    margin-bottom: 1.5rem;
  }

  @media (min-width: 1024px) {
    .stats {
      flex-direction: row;
    }
  }

  .stat {
    padding: 1rem 1.5rem;
    flex: 1;
    text-align: center;
  }

  .stat-value {
    font-size: var(--font-size-2xl, 1.5rem);
    font-weight: 700;
  }

  .stat-title {
    margin-top: 0.5rem;
    opacity: 0.6;
    font-size: var(--font-size-sm);
  }

  .value-info {
    color: var(--color-info);
  }

  .value-warning {
    color: var(--color-warning);
  }

  .value-success {
    color: var(--color-success);
  }

  .value-primary {
    color: var(--color-primary);
  }

  .unit-suffix {
    font-size: 0.4em;
    font-weight: 500;
    margin-left: 0.15em;
  }

  .fraction-suffix {
    font-size: 0.4em;
    font-weight: 400;
    margin-left: 0.15em;
    opacity: 0.5;
    color: var(--color-base-content);
  }

  /* Auto grid */
  .auto-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));
    gap: 1rem;
  }

  /* Year rows */
  .year-row {
    display: flex;
    justify-content: space-between;
    align-items: baseline;
    margin-bottom: 0.5rem;
  }

  .mono-value {
    font-family: var(--font-mono);
    font-size: var(--font-size-sm);
    font-weight: 700;
  }

  .mono-value-semibold {
    font-family: var(--font-mono);
    font-size: var(--font-size-sm);
    font-weight: 600;
  }

  /* Progress bars */
  .progress-bar {
    width: 100%;
    height: 0.5rem;
    appearance: none;
    border-radius: var(--radius-full);
  }

  .progress-bar::-webkit-progress-bar {
    background: var(--color-base-300);
    border-radius: var(--radius-full);
  }

  .progress-primary::-webkit-progress-value {
    background: var(--color-primary);
    border-radius: var(--radius-full);
  }

  .year-progress-block {
    margin-bottom: 1.5rem;
  }

  .progress-details {
    opacity: 0.5;
    font-size: var(--font-size-xs);
    display: flex;
    gap: 1rem;
    margin-top: 0.5rem;
  }

  /* Filter section */
  .filter-section {
    margin-bottom: 1.5rem;
    margin-top: 2.5rem;
  }

  .filter-label {
    font-size: var(--font-size-sm);
    font-weight: 500;
    opacity: 0.7;
    margin-bottom: 0.5rem;
    display: block;
  }

  .search-input-wrapper {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    max-width: 32rem;
    border: 1px solid var(--color-base-300);
    border-radius: var(--radius-field);
    padding: 0.5rem 0.75rem;
    background: var(--color-base-100);
  }

  .search-icon {
    opacity: 0.5;
    flex-shrink: 0;
  }

  .search-input {
    flex: 1;
    border: none;
    outline: none;
    background: transparent;
    font-size: var(--font-size-sm);
    min-width: 0;
  }

  /* Badges */

  /* Empty state */
  .empty-state {
    text-align: center;
    padding: 2rem;
    opacity: 0.6;
  }

  .empty-state svg {
    width: 3rem;
    height: 3rem;
    margin-bottom: 1rem;
  }

  /* Group sections */
  .group-section {
    margin-bottom: 4rem;
  }

  .group-header {
    margin-bottom: 1.5rem;
    padding-bottom: 1rem;
    border-bottom: 1px solid var(--color-base-300);
  }

  .group-title {
    font-size: var(--font-size-xl, 1.25rem);
    margin-bottom: 0.5rem;
  }

  /* Tribunal cards */
  .tribunal-link {
    display: block;
    height: 100%;
    text-decoration: none;
    color: inherit;
  }

  .tribunal-link:hover .tribunal-card {
    border-color: var(--color-accent);
    box-shadow: var(--shadow-md);
  }

  .tribunal-card {
    height: 100%;
    transition: border-color var(--transition-base), box-shadow var(--transition-base);
  }

  .tribunal-card.offline {
    opacity: 0.6;
  }

  .tribunal-card-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 0.5rem;
  }

  .tribunal-card-meta {
    font-size: var(--font-size-xs);
    opacity: 0.7;
  }

  .latest-date {
    display: block;
    margin-top: 0.25rem;
    opacity: 0.7;
  }
</style>
